#!/bin/sh -e

SCRIPT_DIR=$(cd $(dirname "$0") ; pwd -P)
PROJECT_HOME=$(dirname $SCRIPT_DIR)
cd "$PROJECT_HOME"

# Get current branch
branch=`git branch | grep '^*' | cut -f 2 -d ' '`
echo "Current branch is '$branch'"

# Reset to branch
git fetch --all
git reset --hard "origin/$branch"
git pull

