#!/bin/sh

mv "tests/test_ann_01.vcf" tests/integration/ann/
mv "tests/test_ann_integration_01.vcf" tests/integration/ann/
mv "tests/test_ann_02.vcf" tests/integration/ann/
mv "tests/test_ann_03.vcf" tests/integration/ann/
mv "tests/test_ann_04.vcf" tests/integration/ann/
mv "tests/test_apply_05_delete_whole_exon.vcf" tests/integration/apply/
mv "tests/test_apply_06_delete_upstream.vcf" tests/integration/apply/
mv "tests/test_apply_07_delete_upstream.vcf" tests/integration/apply/
mv "tests/test_apply_08_mixed_variant.vcf" tests/integration/apply/
mv "tests/test_apply_09_mixed_variant.vcf" tests/integration/apply/
mv "tests/test_apply_10_mixed_variant.vcf" tests/integration/apply/
mv "tests/integration/cancer/test.cancer.snp.01.vcf" tests/integration/cancer/
mv "tests/integration/cancer/test.cancer_no_ped.vcf" tests/integration/cancer/
mv "tests/integration/cancer/test_cancer_concurrent_modification.vcf"// tests/integration/cancer/
mv "tests/integration/cancer/test_04.vcf" tests/integration/cancer/
mv "tests/empty.vcf" tests/integration/canonical/
mv "tests/canon_geneId2trId_test02.txt" tests/integration/canonical/
mv "tests/empty.vcf" tests/integration/canonical/
mv "tests/missing_coding_tr_tag.vcf" tests/integration/codingTag/
mv "tests/test_ann_01.vcf" tests/integration/config/
mv ,"tests/custom_intervals_01.vcf" tests/integration/cutsomIntervals/
mv "tests/del_multiple_splice_region.vcf" tests/integration/delEtc/
mv "tests/del_multiple_splice_region.vcf" tests/integration/delEtc/
mv "tests/dup_01.vcf" tests/integration/dup/
mv "tests/eff_sort.vcf" tests/integration/eff/
mv "tests/eff_sort_canon.vcf" tests/integration/eff/
mv "tests/eff_sort.vcf" tests/integration/eff/
mv "tests/empty_only_header.vcf" tests/integration/eff/
mv "tests/eff_sort.vcf" tests/integration/eff/
mv "tests/gatk_NO_splice_regions.vcf" tests/integration/eff/
mv "tests/mnp_insertion_at_transcript_end.vcf" tests/integration/eff/
mv "tests/mnp_deletion.vcf" tests/integration/eff/
mv "tests/test_gatk_no_annotations.vcf" tests/integration/eff/
mv "tests/missing_chromo.vcf" tests/integration/errors/
mv "tests/missing_chromo.vcf" tests/integration/errors/
mv "tests/testLukas.vcf" tests/integration/exonFrame/
mv "tests/test_filter_transcripts_001.vcf" tests/integration/filterTranscripts/
mv "tests/test_filter_transcripts_001.vcf" tests/integration/filterTranscripts/
mv "tests/test_01_hgvs_deletions_chr11.vcf" tests/integration/hgvsDel/
mv "tests/hgvs_dup.vcf" tests/integration/hgvsDnaDup/
mv "tests/hgvs_frameshifts_syn_chr1.vcf" tests/integration/hgvsFrameShift/
mv "tests/hgvs_frameshifts_syn_chr4.vcf" tests/integration/hgvsFrameShift/
mv "tests/hgvs_frameshifts_syn_chr10.vcf" tests/integration/hgvsFrameShift/
mv "tests/hgvs_frameshifts_syn_chr17.vcf" tests/integration/hgvsFrameShift/
mv "tests/hgvs_frameshifts_syn_chr19.vcf" tests/integration/hgvsFrameShift/
mv "tests/hgvs_dup.vcf" tests/integration/hgvsHard/
mv "tests/hgvs_md.chr17.vcf" tests/integration/hgvsHard/
mv "tests/hgvs_jeremy_1.vcf" tests/integration/hgvsHard/
mv "tests/hgvs_walk_and_roll.1.vcf" tests/integration/hgvsHard/
mv "tests/hgvs_savant.vcf" tests/integration/hgvsHard/
mv "tests/hgvs_protein_deleteion_length.vcf" tests/integration/hgvsHard/
mv "tests/hgvs_protein_deleteion_length_2.vcf" tests/integration/hgvsHard/
mv "tests/hgvs_ins_dups_chr1.vcf" tests/integration/hgvsIns/
mv "tests/hgvs_ins_dups_chr3.vcf" tests/integration/hgvsIns/
mv "tests/hgvs_ins_dups_chr4.vcf" tests/integration/hgvsIns/
mv "tests/hgvs_ins_dups_chr19.vcf" tests/integration/hgvsIns/
mv "tests/hgvs_ins_chr7.vcf" tests/integration/hgvsIns/
mv "tests/hgvs_ins_07.vcf" tests/integration/hgvsIns/
mv "tests/hgvs_1.vep.vcf" tests/integration/hgvs/
mv "tests/ensembl_hgvs_intron.1.vep.vcf" tests/integration/hgvs/
mv "tests/ensembl_hgvs_intron.outsideCds.vep.vcf" tests/integration/hgvs/
mv "tests/ensembl_hgvs_intron.vep.vcf" tests/integration/hgvs/
mv "tests/ensembl_hgvs_intron.within_cds.vep.vcf" tests/integration/hgvs/
mv "tests/mixed_10_hgvs.vep.vcf" tests/integration/hgvs/
mv "tests/hgvs_counsyl.vcf" tests/integration/hgvs/
mv "tests/hgvs_counsyl.noShift.vcf" tests/integration/hgvs/
mv "tests/test_BRCA_splice_15.vcf" tests/integration/hgvs/
mv "tests/hgvs_splice_region.vcf" tests/integration/hgvs/
mv "tests/test_hgvs_INS_intergenic.vcf" tests/integration/hgvs/
mv "tests/test_large_del_hgvs_13.vcf" tests/integration/hgvsLarge/
mv "tests/hgvs_mnps_01.vcf" tests/integration/hgvsMnps/
mv "tests/hgvs_mnps_02.vcf" tests/integration/hgvsMnps/
mv "tests/hgvs_upstream.vcf" tests/integration/hgvsUpDownStream/
mv "tests/hgvs_downstream.vcf" tests/integration/hgvsUpDownStream/
mv "tests/hgvs_upstream_del.vcf" tests/integration/hgvsUpDownStream/
mv "tests/hgvs_upstream_negative_strand.vcf" tests/integration/hgvsUpDownStream/
mv "tests/hgvs_downstream_negative_strand.vcf" tests/integration/hgvsUpDownStream/
mv "tests/huge_deletion_DEL.vcf" tests/integration/hugeDeletions/
mv "tests/huge_deletion_chr9.vcf" tests/integration/hugeDeletions/
mv "tests/ins_off_by_one.vcf" tests/integration/insEtc/
mv "tests/testENST00000268124_ins_vep.vcf" tests/integration/insVep/
mv "tests/testENST00000445220_ins_vep.vcf" tests/integration/insVep/
mv "tests/hgvs_dup.vcf" tests/integration/markerSeq/
mv "tests/mixed_01.vcf" tests/integration/mixedVariants/
mv "tests/mixed_chr22.vcf" tests/integration/mixedVariants/
mv "tests/mixed_chr14.vcf" tests/integration/mixedVariants/
mv "tests/mixed_chr12.vcf" tests/integration/mixedVariants/
mv "tests/mixed_chr22.vcf" tests/integration/mixedVariants/
mv "tests/mixed_chr7.vcf" tests/integration/mixedVariants/
mv "tests/mixed_chr6.vcf" tests/integration/mixedVariants/
mv "tests/mixed_chr1.vcf" tests/integration/mixedVariants/
mv "tests/mixed_09.vcf" tests/integration/mixedVariants/
mv "tests/mixed_11.vcf" tests/integration/mixedVariants/
mv "tests/test.mnp.01.vcf" tests/integration/mnp/
mv "tests/test_motif_01.vcf" tests/integration/motif/
mv "tests/test_motif_01.vcf" tests/integration/motif/
mv "tests/test_motif_02.vcf" tests/integration/motif/
mv "tests/test_motif_02.vcf" tests/integration/motif/
mv "tests/test_motif_03.vcf" tests/integration/motif/
mv "tests/test_motif_03.vcf" tests/integration/motif/
mv "tests/craig_chr11.vcf" tests/integration/motif/
mv "tests/craig_chr14.vcf" tests/integration/motif/
mv "tests/test_nextProt_02.vcf" tests/integration/nextProt/
mv "tests/test_nextProt_02.vcf" tests/integration/nextProt/
mv "tests/test_nextProt_03.vcf" tests/integration/nextProt/
mv "tests/test_nextProt_03.vcf" tests/integration/nextProt/
mv "tests/test.nextProt_paren.vcf" tests/integration/nextProt/
mv "tests/test.no_change.vcf" tests/integration/noChange/
mv "tests/test.no_change_02.vcf" tests/integration/noChange/
mv "tests/test_interaction_01.vcf" tests/integration/proteinInteraction/
mv "tests/test_interaction_02.vcf" tests/integration/proteinInteraction/
mv "tests/test_interaction_03.vcf" tests/integration/proteinInteraction/
mv "tests/test_regulatory_01.vcf" tests/integration/regulation/
mv "tests/testENST00000268124.SNP.ORI.vcf" tests/integration/sequenceOntology/
mv "tests/testENST00000268124.SNP.vcf" tests/integration/sequenceOntology/
mv "tests/testENST00000268124.SNP.ORI.02.vcf" tests/integration/sequenceOntology/
mv "tests/testENST00000268124.SNP.02.vcf" tests/integration/sequenceOntology/
mv "tests/testENST00000268124.Ins.ORI.03.vcf" tests/integration/sequenceOntology/
mv "tests/testENST00000268124.Ins.03.vcf" tests/integration/sequenceOntology/
mv "tests/testENST00000398332.Ins.ORI.04.vcf" tests/integration/sequenceOntology/
mv "tests/testENST00000398332.Ins.04.vcf" tests/integration/sequenceOntology/
mv "tests/testENST00000268124.Del.ORI.05.vcf" tests/integration/sequenceOntology/
mv "tests/testENST00000268124.Del.05.vcf" tests/integration/sequenceOntology/
mv "tests/testENST00000268124.Mnp.ORI.06.vcf" tests/integration/sequenceOntology/
mv "tests/testENST00000268124.Mnp.06.vcf" tests/integration/sequenceOntology/
mv "tests/test.chr1.1line.out.classic.vcf" tests/integration/snpEff/
mv "tests/test.chr1.1line.vcf" tests/integration/snpEff/
mv "tests/test.chr1.1line.out.classic.vcf" tests/integration/snpEffMultiThread/
mv "tests/test.chr1.1line.vcf" tests/integration/snpEffMultiThread/
mv "tests/test_chrM_start_codon_nonSyn.vcf" tests/integration/snp/
mv "tests/stop_gained_chr2.vcf" tests/integration/snp/
mv "tests/test_chrM_start_codon.vcf" tests/integration/snp/
mv "tests/test_fusion_FGFR3-TACC3.vcf" tests/integration/structural/
mv "tests/test_fusion_EML4-ALK.vcf" tests/integration/structural/
mv "tests/test_fusion_TTC3-DSCAM.vcf" tests/integration/structural/
mv "tests//test_fusion_CCDC6-RET.vcf" tests/integration/structural/
mv "tests/test_fusion_ROS1-SLC34A2.vcf" tests/integration/structural/
mv "tests/test_fusion_intron_rank.vcf" tests/integration/structural/
mv "tests/short_codon_bug.vcf" tests/integration/transcriptError/
mv "tests/incorrect_ref.vcf" tests/integration/transcriptError/
mv "tests/test_vcf_filter.vcf" tests/integration/vcfs/
mv "tests/vcf_genes_spaces.vcf" tests/integration/vcfs/
mv "tests/test_non_variants.vcf" tests/integration/vcfs/
mv "tests/test_fusion_intron_rank.vcf" tests/integration/zzz/
mv "tests/test_old_SO_01.vcf" tests/unity/annParse/
mv "tests/tfbs_ablation.vcf" tests/unity/annParse/
mv "tests/test.chr1.vcf" tests/unity/fileIndexChrPos/
mv "tests/test_filter_transcripts_001.ori.vcf" tests/unity/fileIndexChrPos/
mv "tests/test.chr1.vcf" tests/unity/fileIndexChrPos/
mv "tests/test.chr1.vcf" tests/unity/fileIndexChrPos/
mv "tests/test.chr1.vcf" tests/unity/fileIndexChrPos/
mv "tests/test.chr1.vcf" tests/unity/fileIndexChrPos/
mv "tests/test.chr1.vcf" tests/unity/fileIndexChrPos/
mv "tests/test.chr1.vcf" tests/unity/fileIndexChrPos/
mv "tests/test.chr1.vcf" tests/unity/fileIndexChrPos/
mv "tests/test.chr1.vcf" tests/unity/fileIndexChrPos/
mv "tests/test.chr1.vcf" tests/unity/fileIndexChrPos/
mv "tests/test.chr1.vcf" tests/unity/fileIndexChrPos/
mv "tests/test.chr1.vcf" tests/unity/fileIndexChrPos/
mv "tests/test.chr1.vcf" tests/unity/fileIndexChrPos/
mv "tests/test.chr1.vcf" tests/unity/fileIndexChrPos/
mv "tests/test.chr1.vcf" tests/unity/fileIndexChrPos/
mv "tests/test_haplotype_fs_vcf_01_phase_implicit.vcf" tests/unity/haplotypeDetectionCompFsVcf/
mv "tests/test_haplotype_fs_vcf_01_phased.vcf" tests/unity/haplotypeDetectionCompFsVcf/
mv "tests/test_haplotype_fs_vcf_01_phasegroup.vcf" tests/unity/haplotypeDetectionCompFsVcf/
mv "tests/test_haplotype_fs_vcf_02_phase_implicit.vcf" tests/unity/haplotypeDetectionCompFsVcf/
mv "tests/test_haplotype_fs_vcf_02_phased.vcf" tests/unity/haplotypeDetectionCompFsVcf/
mv "tests/test_haplotype_fs_vcf_02_phasegroup.vcf" tests/unity/haplotypeDetectionCompFsVcf/
mv "tests/test_haplotype_fs_vcf_03.vcf" tests/unity/haplotypeDetectionCompFsVcf/
mv "tests/test_haplotype_fs_vcf_04.vcf" tests/unity/haplotypeDetectionCompFsVcf/
mv "tests/test_haplotype_fs_vcf_01_phase_implicit.vcf" tests/unity/haplotypeDetection/
mv "tests/test_haplotype_fs_vcf_01_phased.vcf" tests/unity/haplotypeDetection/
mv "tests/test_haplotype_fs_vcf_01_phasegroup.vcf" tests/unity/haplotypeDetection/
mv "tests/test_haplotype_fs_vcf_02_phase_implicit.vcf" tests/unity/haplotypeDetection/
mv "tests/test_haplotype_fs_vcf_02_phased.vcf" tests/unity/haplotypeDetection/
mv "tests/test_haplotype_fs_vcf_02_phasegroup.vcf" tests/unity/haplotypeDetection/
mv "tests/test_haplotype_fs_vcf_03.vcf" tests/unity/haplotypeDetection/
mv "tests/test_haplotype_fs_vcf_04.vcf" tests/unity/haplotypeDetection/
mv "tests/test_haplotype_samecodon_vcf_01_phase_implicit.vcf" tests/unity/haplotypeDetectionSameCodonVcf/
mv "tests/test_haplotype_samecodon_vcf_01_phased.vcf" tests/unity/haplotypeDetectionSameCodonVcf/
mv "tests/test_haplotype_samecodon_vcf_01_phasegroup.vcf" tests/unity/haplotypeDetectionSameCodonVcf/
mv "tests/test_haplotype_samecodon_vcf_02_phase_implicit.vcf" tests/unity/haplotypeDetectionSameCodonVcf/
mv "tests/test_haplotype_samecodon_vcf_02_phased.vcf" tests/unity/haplotypeDetectionSameCodonVcf/
mv "tests/test_haplotype_samecodon_vcf_02_phasegroup.vcf" tests/unity/haplotypeDetectionSameCodonVcf/
mv "tests/test_haplotype_samecodon_vcf_03.vcf" tests/unity/haplotypeDetectionSameCodonVcf/
mv "tests/test_haplotype_samecodon_vcf_04.vcf" tests/unity/haplotypeDetectionSameCodonVcf/
mv "tests/testLukas.vcf" tests/unity/seekableReader/
mv "tests/1kg_head.vcf" tests/unity/vcf/
mv "tests/vcf.vcf" tests/unity/vcf/
mv "tests/vcf_04_del.vcf" tests/unity/vcf/
mv "tests/choking_on_dot_slash_dot.vcf" tests/unity/vcf/
mv "tests/array_out_of_bounds.vcf" tests/unity/vcf/
mv "tests/long.vcf" tests/unity/vcf/
mv "tests/alt_del.vcf" tests/unity/vcf/
mv "tests/empty.vcf" tests/unity/vcf/
mv "tests/empty.vcf" tests/unity/vcf/
mv "tests/empty.vcf" tests/unity/vcf/
mv "tests/test.chr1.1line.vcf" tests/unity/vcf/
mv "tests/test.chr1.1line.vcf" tests/unity/vcf/
mv "tests/test.chr1.1line.vcf" tests/unity/vcf/
mv "tests/test.EFF_V2.vcf" tests/unity/vcf/
mv "tests/test.EFF_V3.vcf" tests/unity/vcf/
mv "tests/1kg.indels.vcf" tests/unity/vcf/
mv "tests/out_of_order.vcf" tests/unity/vcf/
mv "tests/test_rasmus.vcf" tests/unity/vcf/
mv "tests/genomic_vcf.gvcf" tests/unity/vcf/
mv "tests/example_42.vcf" tests/unity/vcf/
mv "tests/example_42.vcf" tests/unity/vcf/
mv "tests/example_42.vcf" tests/unity/vcf/
mv "tests/test_vcf_ann_plus_sign.vcf" tests/unity/vcf/
mv "tests/test_gVCF_NON_REF.vcf" tests/unity/vcf/
mv "tests/test_missing_ref.vcf" tests/unity/vcf/
mv "tests/vcf_translocation.vcf" tests/unity/vcf/
mv "tests/vcf_translocation_parsing.vcf" tests/unity/vcf/
