
chr6:
		OK

6_GL000251v2_alt

		ERROR: CDSs do not match for transcript NM_002117.5	Strand:true	Exons: 8
			SnpEff CDS  (  1101) : 'atgcgggtcatggcgccccgagccctcctcctgctgctctcgggaggcctggccctgaccgagacctgggcctgctcccactccatgaggtatttcgacaccgccgtgtcccggcccggccgcggagagccccgcttcatctcagtgggctacgtggacgacacgcagttcgtgcggttcgacagcgacgccgcgagtccgagaggggagccgcgggcgccgtgggtggagcaggaggggccggagtattgggaccgggagacacagaactacaagcgccaggcacaggctgaccgagtgagcctgcggaacctgcgcggctactacaaccagagcgaggacgggtctcacaccctccagaggatgtatggctgcgacctggggcccgacgggcgcctcctccgcgggtatgaccagtccgcctacgacggcaaggattacatcgccctgaacgaggacctgcgctcctggaccgccgcggacaccgcggctcagatcacccagcgcaagttggaggcggcccgtgcggcggagcagctgagagcctacctggagggcacgtgcgtggagtggctccgcagatacctggagaacgggaaggagacgctgcagcgcgcagaacccccaaagacacacgtgacccaccaccccctctctgaccatgaggccaccctgaggtgctgggccctgggcttctaccctgcggagatcacactgacctggcagcgggatggggaggaccagacccaggacaccgagcttgtggagaccaggccagcaggagatggaaccttccagaagtgggcagctgtggtggtgccttctggacaagagcagagatacacgtgccatatgcagcacgaggggctgcaagagcccctcaccctgagctgggagccatcttcccagcccaccatccccatcatgggcatcgttgctggcctggctgtcctggttgtcctagctgtccttggagctgtggtcaccgctatgatgtgtaggaggaagagctcaggtggaaaaggagggagctgctctcaggctgcgtgcagcaacagtgcccagggctctgatgagtctctcatcacttgtaaagcctga'
			Reference   (  1586) : 'tccgcagtcccggttctaaagtccccagtcacccacccggactcacattctccccagaggccgagatgcgggtcatggcgccccgagccctcctcctgctgctctcgggaggcctggccctgaccgagacctgggcctgctcccactccatgaggtatttcgacaccgccgtgtcccggcccggccgcggagagccccgcttcatctcagtgggctacgtggacgacacgcagttcgtgcggttcgacagcgacgccgcgagtccgagaggggagccgcgggcgccgtgggtggagcaggaggggccggagtattgggaccgggagacacagaagtacaagcgccaggcacaggctgaccgagtgagcctgcggaacctgcgcggctactacaaccagagcgaggacgggtctcacaccctccagaggatgtctggctgcgacctggggcccgacgggcgcctcctccgcgggtatgaccagtccgcctacgacggcaaggattacatcgccctgaacgaggacctgcgctcctggaccgccgcggacaccgcggctcagatcacccagcgcaagttggaggcggcccgtgcggcggagcagctgagagcctacctggagggcacgtgcgtggagtggctccgcagatacctggagaacgggaaggagacgctgcagcgcgcagaacccccaaagacacacgtgacccaccaccccctctctgaccatgaggccaccctgaggtgctgggccctgggcttctaccctgcggagatcacactgacctggcagcgggatggggaggaccagacccaggacaccgagcttgtggagaccaggccagcaggagatggaaccttccagaagtgggcagctgtggtggtgccttctggacaagagcagagatacacgtgccatatgcagcacgaggggctgcaagagcccctcaccctgagctgggagccatcttcccagcccaccatccccatcatgggcatcgttgctggcctggctgtcctggttgtcctagctgtccttggagctgtggtcaccgctatgatgtgtaggaggaagagctcaggtggaaaaggagggagctgctctcaggctgcgtgcagcaacagtgcccagggctctgatgagtctctcatcacttgtaaagcctgagacagctgcctgtgtgggactgagatgcaggatttcttcacacctctcctttgtgacttcaagagcctctggcatctctttctgcaaaggcacctgaatgtgtctgcgttcctgttagcataatgtgaggaggtggagagacagcccacccccgtgtccaccgtgacccctgtccccacactgacctgtgttccctccccgatcatctttcctgttccagagaggtggggctggatgtctccatctctgtctcaaattcatggtgcactgagctgcaacttcttacttccctaatgaagttaagaacctgaatataaatttgtgttctcaaatatttgctatgaagcgttgatggattaattaaataagtcaattcctagaagttgagagagcaaataaagacctgagaaccttccagaa'
			Alignment (Snpeff CDS vs Reference CDS).	Score: 1097	Max. possible score: 1101	Diff: 4
			-----------------------------------------------------------------ATGCGGGTCATGGCGCCCCGAGCCCTCCTCCTGCTGCTCTCGGGAGGCCTGGCCCTGACCGAGACCTGGGCCTGCTCCCACTCCATGAGGTATTTCGACACCGCCGTGTCCCGGCCCGGCCGCGGAGAGCCCCGCTTCATCTCAGTGGGCTACGTGGACGACACGCAGTTCGTGCGGTTCGACAGCGACGCCGCGAGTCCGAGAGGGGAGCCGCGGGCGCCGTGGGTGGAGCAGGAGGGGCCGGAGTATTGGGACCGGGAGACACAGAACTACAAGCGCCAGGCACAGGCTGACCGAGTGAGCCTGCGGAACCTGCGCGGCTACTACAACCAGAGCGAGGACGGGTCTCACACCCTCCAGAGGATGTATGGCTGCGACCTGGGGCCCGACGGGCGCCTCCTCCGCGGGTATGACCAGTCCGCCTACGACGGCAAGGATTACATCGCCCTGAACGAGGACCTGCGCTCCTGGACCGCCGCGGACACCGCGGCTCAGATCACCCAGCGCAAGTTGGAGGCGGCCCGTGCGGCGGAGCAGCTGAGAGCCTACCTGGAGGGCACGTGCGTGGAGTGGCTCCGCAGATACCTGGAGAACGGGAAGGAGACGCTGCAGCGCGCAGAACCCCCAAAGACACACGTGACCCACCACCCCCTCTCTGACCATGAGGCCACCCTGAGGTGCTGGGCCCTGGGCTTCTACCCTGCGGAGATCACACTGACCTGGCAGCGGGATGGGGAGGACCAGACCCAGGACACCGAGCTTGTGGAGACCAGGCCAGCAGGAGATGGAACCTTCCAGAAGTGGGCAGCTGTGGTGGTGCCTTCTGGACAAGAGCAGAGATACACGTGCCATATGCAGCACGAGGGGCTGCAAGAGCCCCTCACCCTGAGCTGGGAGCCATCTTCCCAGCCCACCATCCCCATCATGGGCATCGTTGCTGGCCTGGCTGTCCTGGTTGTCCTAGCTGTCCTTGGAGCTGTGGTCACCGCTATGATGTGTAGGAGGAAGAGCTCAGGTGGAAAAGGAGGGAGCTGCTCTCAGGCTGCGTGCAGCAACAGTGCCCAGGGCTCTGATGAGTCTCTCATCACTTGTAAAGCCTGA                                                                                                                                                                                                                                                                                                                                                                                                                                    
																			 |||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||*|||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||*|||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||                                                                                                                                                                                                                                                                                                                                                                                                                                    
			TCCGCAGTCCCGGTTCTAAAGTCCCCAGTCACCCACCCGGACTCACATTCTCCCCAGAGGCCGAGATGCGGGTCATGGCGCCCCGAGCCCTCCTCCTGCTGCTCTCGGGAGGCCTGGCCCTGACCGAGACCTGGGCCTGCTCCCACTCCATGAGGTATTTCGACACCGCCGTGTCCCGGCCCGGCCGCGGAGAGCCCCGCTTCATCTCAGTGGGCTACGTGGACGACACGCAGTTCGTGCGGTTCGACAGCGACGCCGCGAGTCCGAGAGGGGAGCCGCGGGCGCCGTGGGTGGAGCAGGAGGGGCCGGAGTATTGGGACCGGGAGACACAGAAGTACAAGCGCCAGGCACAGGCTGACCGAGTGAGCCTGCGGAACCTGCGCGGCTACTACAACCAGAGCGAGGACGGGTCTCACACCCTCCAGAGGATGTCTGGCTGCGACCTGGGGCCCGACGGGCGCCTCCTCCGCGGGTATGACCAGTCCGCCTACGACGGCAAGGATTACATCGCCCTGAACGAGGACCTGCGCTCCTGGACCGCCGCGGACACCGCGGCTCAGATCACCCAGCGCAAGTTGGAGGCGGCCCGTGCGGCGGAGCAGCTGAGAGCCTACCTGGAGGGCACGTGCGTGGAGTGGCTCCGCAGATACCTGGAGAACGGGAAGGAGACGCTGCAGCGCGCAGAACCCCCAAAGACACACGTGACCCACCACCCCCTCTCTGACCATGAGGCCACCCTGAGGTGCTGGGCCCTGGGCTTCTACCCTGCGGAGATCACACTGACCTGGCAGCGGGATGGGGAGGACCAGACCCAGGACACCGAGCTTGTGGAGACCAGGCCAGCAGGAGATGGAACCTTCCAGAAGTGGGCAGCTGTGGTGGTGCCTTCTGGACAAGAGCAGAGATACACGTGCCATATGCAGCACGAGGGGCTGCAAGAGCCCCTCACCCTGAGCTGGGAGCCATCTTCCCAGCCCACCATCCCCATCATGGGCATCGTTGCTGGCCTGGCTGTCCTGGTTGTCCTAGCTGTCCTTGGAGCTGTGGTCACCGCTATGATGTGTAGGAGGAAGAGCTCAGGTGGAAAAGGAGGGAGCTGCTCTCAGGCTGCGTGCAGCAACAGTGCCCAGGGCTCTGATGAGTCTCTCATCACTTGTAAAGCCTGA                                                                                                                                                                                                                                                                                                                                                                                                                                    
		Transcript details:
		6_GL000251v2_alt:2749674-2753061, strand: -, id:NM_002117.5, Protein
				5'UTR   :	6_GL000251v2_alt	2752997-2753061 UTR_5_PRIME 'NM_002117.5.ex.8'
				Exons:
				6_GL000251v2_alt:2749674-2750098 'NM_002117.5.ex.1', rank: 8, frame: 2, sequence: cctgagacagctgcctgtgtgggactgagatgcaggatttcttcacacctctcctttgtgacttcaagagcctctggcatctctttctgcaaaggcgtctgaatgtgtctgcgttcctgttagcataatgtgaggaggtggagagacagcccacccccgtgtccaccgtgacccctgtccccacactgacctgtgttccctccccgatcatctttcctgttccagagaggtggggctggatgtctccatctctgtctcaaattcatggtgcactgagctgcaacttcttacttccctaatgaagttaagaacctgaatataaatttgtgttctcaaatatttgctatgaagcgttgatggattaattaaataagtcaattcctagaagttgagagagcaaataaagacctgagaaccttccagaa
				6_GL000251v2_alt:2750263-2750310 'NM_002117.5.ex.2', rank: 7, frame: 2, sequence: gcagcaacagtgcccagggctctgatgagtctctcatcacttgtaaag
				6_GL000251v2_alt:2750418-2750450 'NM_002117.5.ex.3', rank: 6, frame: 2, sequence: gtggaaaaggagggagctgctctcaggctgcgt
				6_GL000251v2_alt:2750891-2751010 'NM_002117.5.ex.4', rank: 5, frame: 2, sequence: agccatcttcccagcccaccatccccatcatgggcatcgttgctggcctggctgtcctggttgtcctagctgtccttggagctgtggtcaccgctatgatgtgtaggaggaagagctcag
				6_GL000251v2_alt:2751135-2751410 'NM_002117.5.ex.5', rank: 4, frame: 2, sequence: aacccccaaagacacacgtgacccaccaccccctctctgaccatgaggccaccctgaggtgctgggccctgggcttctaccctgcggagatcacactgacctggcagcgggatggggaggaccagacccaggacaccgagcttgtggagaccaggccagcaggagatggaaccttccagaagtgggcagctgtggtggtgccttctggacaagagcagagatacacgtgccatatgcagcacgaggggctgcaagagcccctcaccctgagctggg
				6_GL000251v2_alt:2751998-2752273 'NM_002117.5.ex.6', rank: 3, frame: 2, sequence: ggtctcacaccctccagaggatgtatggctgcgacctggggcccgacgggcgcctcctccgcgggtatgaccagtccgcctacgacggcaaggattacatcgccctgaacgaggacctgcgctcctggaccgccgcggacaccgcggctcagatcacccagcgcaagttggaggcggcccgtgcggcggagcagctgagagcctacctggagggcacgtgcgtggagtggctccgcagatacctggagaacgggaaggagacgctgcagcgcgcag
				6_GL000251v2_alt:2752524-2752793 'NM_002117.5.ex.7', rank: 2, frame: 2, sequence: gctcccactccatgaggtatttcgacaccgccgtgtcccggcccggccgcggagagccccgcttcatctcagtgggctacgtggacgacacgcagttcgtgcggttcgacagcgacgccgcgagtccgagaggggagccgcgggcgccgtgggtggagcaggaggggccggagtattgggaccgggagacacagaactacaagcgccaggcacaggctgaccgagtgagcctgcggaacctgcgcggctactacaaccagagcgaggacg
				6_GL000251v2_alt:2752924-2753061 'NM_002117.5.ex.8', rank: 1, frame: 0, sequence: tccgcagtcccggttctaaagtccccagtcacccacccggactcacattctccccagaggccgagatgcgggtcatggcgccccgagccctcctcctgctgctctcgggaggcctggccctgaccgagacctgggcct
				3'UTR   :	6_GL000251v2_alt	2749674-2750093 UTR_3_PRIME 'NM_002117.5.ex.1'
				CDS     :	atgcgggtcatggcgccccgagccctcctcctgctgctctcgggaggcctggccctgaccgagacctgggcctgctcccactccatgaggtatttcgacaccgccgtgtcccggcccggccgcggagagccccgcttcatctcagtgggctacgtggacgacacgcagttcgtgcggttcgacagcgacgccgcgagtccgagaggggagccgcgggcgccgtgggtggagcaggaggggccggagtattgggaccgggagacacagaactacaagcgccaggcacaggctgaccgagtgagcctgcggaacctgcgcggctactacaaccagagcgaggacgggtctcacaccctccagaggatgtatggctgcgacctggggcccgacgggcgcctcctccgcgggtatgaccagtccgcctacgacggcaaggattacatcgccctgaacgaggacctgcgctcctggaccgccgcggacaccgcggctcagatcacccagcgcaagttggaggcggcccgtgcggcggagcagctgagagcctacctggagggcacgtgcgtggagtggctccgcagatacctggagaacgggaaggagacgctgcagcgcgcagaacccccaaagacacacgtgacccaccaccccctctctgaccatgaggccaccctgaggtgctgggccctgggcttctaccctgcggagatcacactgacctggcagcgggatggggaggaccagacccaggacaccgagcttgtggagaccaggccagcaggagatggaaccttccagaagtgggcagctgtggtggtgccttctggacaagagcagagatacacgtgccatatgcagcacgaggggctgcaagagcccctcaccctgagctgggagccatcttcccagcccaccatccccatcatgggcatcgttgctggcctggctgtcctggttgtcctagctgtccttggagctgtggtcaccgctatgatgtgtaggaggaagagctcaggtggaaaaggagggagctgctctcaggctgcgtgcagcaacagtgcccagggctctgatgagtctctcatcacttgtaaagcctga
				Protein :	MRVMAPRALLLLLSGGLALTETWACSHSMRYFDTAVSRPGRGEPRFISVGYVDDTQFVRFDSDAASPRGEPRAPWVEQEGPEYWDRETQNYKRQAQADRVSLRNLRGYYNQSEDGSHTLQRMYGCDLGPDGRLLRGYDQSAYDGKDYIALNEDLRSWTAADTAAQITQRKLEAARAAEQLRAYLEGTCVEWLRRYLENGKETLQRAEPPKTHVTHHPLSDHEATLRCWALGFYPAEITLTWQRDGEDQTQDTELVETRPAGDGTFQKWAAVVVPSGQEQRYTCHMQHEGLQEPLTLSWEPSSQPTIPIMGIVAGLAVLVVLAVLGAVVTAMMCRRKSSGGKGGSCSQAACSNSAQGSDESLITCKA*

6_GL000252v2_alt

		Frame correction: Position Transcript_6_GL000252v2_alt:2526549-2529926Transcript 'NM_002117.5.6'	Exon rank 6	Expected frame: 0	Exon frame: 2	Sequence len: 981

		ERROR: CDSs do not match for transcript NM_002117.5	Strand:true	Exons: 9
			SnpEff CDS  (  1089) : 'atgcgggtcatggcgccccgaaccctcatcctgctgctctcgggagccctggccctgaccgagacctgggcctgctcccactccatgaggtatttcgacaccgccgtgtcccggcccggccgcggagagccccgcttcatctcagtgggctacgtggacgacacgcagttcgtgcggttcgacagcgacgccgcgagtccgagaggggagccccgggcgccgtgggtggagcaggaggggccggagtattgggaccgggagacacagaagtacaagcgccaggcacaggctgaccgagtgaacctgcggaaactgcgcggctactacaaccagagcgaggacgggtctcacaccctccagtggatgtatggctgcgacctggggcccgacgggcgcctcctccgcgggtatgaccagtccgcctacgacggcaaggattacatcgccctgaacgaggacctgcgctcctggaccgccgcggacacggcggctcagatcacccagcgcaagtgggaggcggcccgtgaggcggagcagtggagagcctacctggagggcacgtgcgtggagtggctccgcagatacctggagaacgggaaggagacgctgcagcgcgcagaacacccaaagacacacgtgacccaccatcccgtctctgaccatgaggccaccctgaggtgctgggccctgggcttctaccctgcggagatcacactgacctggcagcgggatggcgaggaccaaactcaggacaccgagcttgtggagaccaggccagcaggagatggaaccttccagaagtgggcagctgtggtggtgccttctggagaagagcagagatacacgtgccatgtgcagcacgaggggctgccagagcccctcaccctgagatgggagccatcttcccagcccaccatccccatcgtgggcatcgttgctggcctggctgtcctggctgtcctagctgtcctaggagctgtgatgtgtaggaggaagagctcaggtggaaaaggagggagctgctctcaggctgcgtgcagcaacagtgcccagggctctgatgagtctctcatcgcttgtaaagcctga'
			Reference   (  1586) : 'tccgcagtcccggttctaaagtccccagtcacccacccggactcacattctccccagaggccgagatgcgggtcatggcgccccgagccctcctcctgctgctctcgggaggcctggccctgaccgagacctgggcctgctcccactccatgaggtatttcgacaccgccgtgtcccggcccggccgcggagagccccgcttcatctcagtgggctacgtggacgacacgcagttcgtgcggttcgacagcgacgccgcgagtccgagaggggagccgcgggcgccgtgggtggagcaggaggggccggagtattgggaccgggagacacagaagtacaagcgccaggcacaggctgaccgagtgagcctgcggaacctgcgcggctactacaaccagagcgaggacgggtctcacaccctccagaggatgtctggctgcgacctggggcccgacgggcgcctcctccgcgggtatgaccagtccgcctacgacggcaaggattacatcgccctgaacgaggacctgcgctcctggaccgccgcggacaccgcggctcagatcacccagcgcaagttggaggcggcccgtgcggcggagcagctgagagcctacctggagggcacgtgcgtggagtggctccgcagatacctggagaacgggaaggagacgctgcagcgcgcagaacccccaaagacacacgtgacccaccaccccctctctgaccatgaggccaccctgaggtgctgggccctgggcttctaccctgcggagatcacactgacctggcagcgggatggggaggaccagacccaggacaccgagcttgtggagaccaggccagcaggagatggaaccttccagaagtgggcagctgtggtggtgccttctggacaagagcagagatacacgtgccatatgcagcacgaggggctgcaagagcccctcaccctgagctgggagccatcttcccagcccaccatccccatcatgggcatcgttgctggcctggctgtcctggttgtcctagctgtccttggagctgtggtcaccgctatgatgtgtaggaggaagagctcaggtggaaaaggagggagctgctctcaggctgcgtgcagcaacagtgcccagggctctgatgagtctctcatcacttgtaaagcctgagacagctgcctgtgtgggactgagatgcaggatttcttcacacctctcctttgtgacttcaagagcctctggcatctctttctgcaaaggcacctgaatgtgtctgcgttcctgttagcataatgtgaggaggtggagagacagcccacccccgtgtccaccgtgacccctgtccccacactgacctgtgttccctccccgatcatctttcctgttccagagaggtggggctggatgtctccatctctgtctcaaattcatggtgcactgagctgcaacttcttacttccctaatgaagttaagaacctgaatataaatttgtgttctcaaatatttgctatgaagcgttgatggattaattaaataagtcaattcctagaagttgagagagcaaataaagacctgagaaccttccagaa'
			Alignment (Snpeff CDS vs Reference CDS).	Score: 1011	Max. possible score: 1089	Diff: 78
			-----------------------------------------------------------------ATGCGGGTCATGGCGCCCCGAACCCTCATCCTGCTGCTCTCGGGAGCCCTGGCCCTGACCGAGACCTGGGCCTGCTCCCACTCCATGAGGTATTTCGACACCGCCGTGTCCCGGCCCGGCCGCGGAGAGCCCCGCTTCATCTCAGTGGGCTACGTGGACGACACGCAGTTCGTGCGGTTCGACAGCGACGCCGCGAGTCCGAGAGGGGAGCCCCGGGCGCCGTGGGTGGAGCAGGAGGGGCCGGAGTATTGGGACCGGGAGACACAGAAGTACAAGCGCCAGGCACAGGCTGACCGAGTGAACCTGCGGAAACTGCGCGGCTACTACAACCAGAGCGAGGACGGGTCTCACACCCTCCAGTGGATGTATGGCTGCGACCTGGGGCCCGACGGGCGCCTCCTCCGCGGGTATGACCAGTCCGCCTACGACGGCAAGGATTACATCGCCCTGAACGAGGACCTGCGCTCCTGGACCGCCGCGGACACGGCGGCTCAGATCACCCAGCGCAAGTGGGAGGCGGCCCGTGAGGCGGAGCAGTGGAGAGCCTACCTGGAGGGCACGTGCGTGGAGTGGCTCCGCAGATACCTGGAGAACGGGAAGGAGACGCTGCAGCGCGCAGAACACCCAAAGACACACGTGACCCACCATCCCGTCTCTGACCATGAGGCCACCCTGAGGTGCTGGGCCCTGGGCTTCTACCCTGCGGAGATCACACTGACCTGGCAGCGGGATGGCGAGGACCAAACTCAGGACACCGAGCTTGTGGAGACCAGGCCAGCAGGAGATGGAACCTTCCAGAAGTGGGCAGCTGTGGTGGTGCCTTCTGGAGAAGAGCAGAGATACACGTGCCATGTGCAGCACGAGGGGCTGCCAGAGCCCCTCACCCTGAGATGGGAGCCATCTTCCCAGCCCACCATCCCCATCGTGGGCATCGTTGCTGGCCTGGCTGTCCTGGCTGTCCTAGCTGTCCTAGGAGCTGTG---A----T--G-TGT--AGGAGGAAGAGCTCAGGTGGAAAAGGAGGGAGCTGCTCTCAGGCTGCGTGCAGCAACAGTGCCCAGGGCTCTGATGAGTCTCTCATCGCTTGTAAAGCCTGA                                                                                                                                                                                                                                                                                                                                                                                                                                    
																			 |||||||||||||||||||||*|||||*||||||||||||||||||*|||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||*||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||*|||||||||*||||||||||||||||||||||||||||||||||||||||||||||||*||||||*|||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||*|||||||||||||||||||||||||*||||||||||||||*||||||||||**|||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||*||||||||||||||||||||||||*|||*||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||*||||||||*||*|||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||*|||||||||||||||||||||||*||||||||||||||||||*||||||||||||||||||*|||||||||||||||||||||||||||||||||*||||||||||||||||||||||||||||||*|||||||||||||||*|||||||||   |    |  | |||  |||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||*||||||||||||||                                                                                                                                                                                                                                                                                                                                                                                                                                    
			TCCGCAGTCCCGGTTCTAAAGTCCCCAGTCACCCACCCGGACTCACATTCTCCCCAGAGGCCGAGATGCGGGTCATGGCGCCCCGAGCCCTCCTCCTGCTGCTCTCGGGAGGCCTGGCCCTGACCGAGACCTGGGCCTGCTCCCACTCCATGAGGTATTTCGACACCGCCGTGTCCCGGCCCGGCCGCGGAGAGCCCCGCTTCATCTCAGTGGGCTACGTGGACGACACGCAGTTCGTGCGGTTCGACAGCGACGCCGCGAGTCCGAGAGGGGAGCCGCGGGCGCCGTGGGTGGAGCAGGAGGGGCCGGAGTATTGGGACCGGGAGACACAGAAGTACAAGCGCCAGGCACAGGCTGACCGAGTGAGCCTGCGGAACCTGCGCGGCTACTACAACCAGAGCGAGGACGGGTCTCACACCCTCCAGAGGATGTCTGGCTGCGACCTGGGGCCCGACGGGCGCCTCCTCCGCGGGTATGACCAGTCCGCCTACGACGGCAAGGATTACATCGCCCTGAACGAGGACCTGCGCTCCTGGACCGCCGCGGACACCGCGGCTCAGATCACCCAGCGCAAGTTGGAGGCGGCCCGTGCGGCGGAGCAGCTGAGAGCCTACCTGGAGGGCACGTGCGTGGAGTGGCTCCGCAGATACCTGGAGAACGGGAAGGAGACGCTGCAGCGCGCAGAACCCCCAAAGACACACGTGACCCACCACCCCCTCTCTGACCATGAGGCCACCCTGAGGTGCTGGGCCCTGGGCTTCTACCCTGCGGAGATCACACTGACCTGGCAGCGGGATGGGGAGGACCAGACCCAGGACACCGAGCTTGTGGAGACCAGGCCAGCAGGAGATGGAACCTTCCAGAAGTGGGCAGCTGTGGTGGTGCCTTCTGGACAAGAGCAGAGATACACGTGCCATATGCAGCACGAGGGGCTGCAAGAGCCCCTCACCCTGAGCTGGGAGCCATCTTCCCAGCCCACCATCCCCATCATGGGCATCGTTGCTGGCCTGGCTGTCCTGGTTGTCCTAGCTGTCCTTGGAGCTGTGGTCACCGCTATGATGTGTAGGAGGAAGAGCTCAGGTGGAAAAGGAGGGAGCTGCTCTCAGGCTGCGTGCAGCAACAGTGCCCAGGGCTCTGATGAGTCTCTCATCACTTGTAAAGCCTGA                                                                                                                                                                                                                                                                                                                                                                                                                                    
		Transcript details:
		6_GL000252v2_alt:2526548-2529925, strand: -, id:NM_002117.5, Protein
				5'UTR   :	6_GL000252v2_alt	2529861-2529925 UTR_5_PRIME 'NM_002117.5.ex.9'
				Exons:
				6_GL000252v2_alt:2526548-2526970 'NM_002117.5.ex.1', rank: 9, frame: 2, sequence: cctgagacagctgcctgtgtgggactgagatgcaggatttcttcacacctctcctttgtgacttcaagagcctctggcatctctttctgcaaaggcatctgaatgtgtctgcgttcctgttagcataatgtgaggaggtggagagacagcccacccccgtgtccaccgtgacccctgtccccacactgacctgtgttccctccccgatcatctttcctgttccagagaagtgggctggatgtctccatctctgtctcaactttacgtgtactgagctgcaacttcttacttccctactgaaaataagaatctgaatataaatttgttttctcaaatatttgctatgagaggttgatggattaattaaataagtcaattcctggaagttgagagagcaaataaagacctgagaaccttccagaa
				6_GL000252v2_alt:2527135-2527181 'NM_002117.5.ex.2', rank: 8, frame: 1, sequence: cagcaacagtgcccagggctctgatgagtctctcatcgcttgtaaag
				6_GL000252v2_alt:2527289-2527322 'NM_002117.5.ex.3', rank: 7, frame: 2, sequence: gtggaaaaggagggagctgctctcaggctgcgtg
				6_GL000252v2_alt:2527762-2527783 'NM_002117.5.ex.4', rank: 6, frame: 0, sequence: atgtgtaggaggaagagctcag
				6_GL000252v2_alt:2527796-2527881 'NM_002117.5.ex.5', rank: 5, frame: 2, sequence: agccatcttcccagcccaccatccccatcgtgggcatcgttgctggcctggctgtcctggctgtcctagctgtcctaggagctgtg
				6_GL000252v2_alt:2528003-2528280 'NM_002117.5.ex.6', rank: 4, frame: 1, sequence: agaacacccaaagacacacgtgacccaccatcccgtctctgaccatgaggccaccctgaggtgctgggccctgggcttctaccctgcggagatcacactgacctggcagcgggatggcgaggaccaaactcaggacaccgagcttgtggagaccaggccagcaggagatggaaccttccagaagtgggcagctgtggtggtgccttctggagaagagcagagatacacgtgccatgtgcagcacgaggggctgccagagcccctcaccctgagatggg
				6_GL000252v2_alt:2528868-2529141 'NM_002117.5.ex.7', rank: 3, frame: 2, sequence: ggtctcacaccctccagtggatgtatggctgcgacctggggcccgacgggcgcctcctccgcgggtatgaccagtccgcctacgacggcaaggattacatcgccctgaacgaggacctgcgctcctggaccgccgcggacacggcggctcagatcacccagcgcaagtgggaggcggcccgtgaggcggagcagtggagagcctacctggagggcacgtgcgtggagtggctccgcagatacctggagaacgggaaggagacgctgcagcgcgc
				6_GL000252v2_alt:2529388-2529657 'NM_002117.5.ex.8', rank: 2, frame: 2, sequence: gctcccactccatgaggtatttcgacaccgccgtgtcccggcccggccgcggagagccccgcttcatctcagtgggctacgtggacgacacgcagttcgtgcggttcgacagcgacgccgcgagtccgagaggggagccccgggcgccgtgggtggagcaggaggggccggagtattgggaccgggagacacagaagtacaagcgccaggcacaggctgaccgagtgaacctgcggaaactgcgcggctactacaaccagagcgaggacg
				6_GL000252v2_alt:2529788-2529925 'NM_002117.5.ex.9', rank: 1, frame: 0, sequence: tccgcagtcccggttctaaagtccccagtcacccacccggactcggattctccccagacgccgagatgcgggtcatggcgccccgaaccctcatcctgctgctctcgggagccctggccctgaccgagacctgggcct
				3'UTR   :	6_GL000252v2_alt	2526548-2526965 UTR_3_PRIME 'NM_002117.5.ex.1'
				CDS     :	atgcgggtcatggcgccccgaaccctcatcctgctgctctcgggagccctggccctgaccgagacctgggcctgctcccactccatgaggtatttcgacaccgccgtgtcccggcccggccgcggagagccccgcttcatctcagtgggctacgtggacgacacgcagttcgtgcggttcgacagcgacgccgcgagtccgagaggggagccccgggcgccgtgggtggagcaggaggggccggagtattgggaccgggagacacagaagtacaagcgccaggcacaggctgaccgagtgaacctgcggaaactgcgcggctactacaaccagagcgaggacgggtctcacaccctccagtggatgtatggctgcgacctggggcccgacgggcgcctcctccgcgggtatgaccagtccgcctacgacggcaaggattacatcgccctgaacgaggacctgcgctcctggaccgccgcggacacggcggctcagatcacccagcgcaagtgggaggcggcccgtgaggcggagcagtggagagcctacctggagggcacgtgcgtggagtggctccgcagatacctggagaacgggaaggagacgctgcagcgcgcagaacacccaaagacacacgtgacccaccatcccgtctctgaccatgaggccaccctgaggtgctgggccctgggcttctaccctgcggagatcacactgacctggcagcgggatggcgaggaccaaactcaggacaccgagcttgtggagaccaggccagcaggagatggaaccttccagaagtgggcagctgtggtggtgccttctggagaagagcagagatacacgtgccatgtgcagcacgaggggctgccagagcccctcaccctgagatgggagccatcttcccagcccaccatccccatcgtgggcatcgttgctggcctggctgtcctggctgtcctagctgtcctaggagctgtgatgtgtaggaggaagagctcaggtggaaaaggagggagctgctctcaggctgcgtgcagcaacagtgcccagggctctgatgagtctctcatcgcttgtaaagcctga
				Protein :	MRVMAPRTLILLLSGALALTETWACSHSMRYFDTAVSRPGRGEPRFISVGYVDDTQFVRFDSDAASPRGEPRAPWVEQEGPEYWDRETQKYKRQAQADRVNLRKLRGYYNQSEDGSHTLQWMYGCDLGPDGRLLRGYDQSAYDGKDYIALNEDLRSWTAADTAAQITQRKWEAAREAEQWRAYLEGTCVEWLRRYLENGKETLQRAEHPKTHVTHHPVSDHEATLRCWALGFYPAEITLTWQRDGEDQTQDTELVETRPAGDGTFQKWAAVVVPSGEEQRYTCHVQHEGLPEPLTLRWEPSSQPTIPIVGIVAGLAVLAVLAVLGAVMCRRKSSGGKGGSCSQAACSNSAQGSDESLIACKA*

6_GL000253v2_alt

		Frame correction: Position Transcript_6_GL000253v2_alt:2577801-2581178Transcript 'NM_002117.5.7'	Exon rank 6	Expected frame: 1	Exon frame: 0	Sequence len: 983

		ERROR: CDSs do not match for transcript NM_002117.5	Strand:true	Exons: 9
			SnpEff CDS  (  1089) : 'atgcgggtcatggcgccccgaaccctcatcctgctgctctcgggagccctggccctgaccgagacctgggcctgctcccactccatgaggtatttctacaccgccgtgtcccggcccggccgcggagagccccgcttcatcgcagtgggctacgtggacgacacgcagttcgtgcggttcgacagcgacgccgcgagtccaagaggggagccgcgggcgccgtgggtggagcaggaggggccggagtattgggaccgggagacacagaagtacaagcgccaggcacagactgaccgagtgagcctgcggaacctgcgcggctactacaaccagagcgaggccgggtctcacaccctccagtggatgtatggctgcgacctggggcccgacgggcgcctcctccgcgggtatgaccagtccgcctacgacggcaaggattacatcgccctgaacgaggacctgcgctcctggaccgccgcggacacggcggctcagatcacccagcgcaagtgggaggcggcccgtgcggcggagcagcagagagcctacctggagggcacgtgcgtggagtggctccgcagatacctggagaacgggaaggagacgctgcagcgcgcagaacacccaaagacacacgtgacccaccatctcgtctctgaccatgaggccaccctgaggtgctgggccctgggcttctaccctgcggagatcacactgacctggcagcgggatggcgaggaccaaactcaggacaccgagcttgtggagaccaggccagcaggagatggaaccttccagaagtgggcagctgtggtggtgccttctggagaagagcagagatacacgtgccatgtgcagcacgaggggctgccggagcccctcaccctgagatgggagccatcttcccagcccaccatccccatcgtgggcatcgttgctggcctggctgtcctggctgtcctagctgtcctaggagctgtggtgtgtaggaggaagagctcaggtggaaaaggagggagctgctctcaggctgcgtgcagcaacagtgcccagggctctgatgagtctctcatcgcttgtaaagcctga'
			Reference   (  1586) : 'tccgcagtcccggttctaaagtccccagtcacccacccggactcacattctccccagaggccgagatgcgggtcatggcgccccgagccctcctcctgctgctctcgggaggcctggccctgaccgagacctgggcctgctcccactccatgaggtatttcgacaccgccgtgtcccggcccggccgcggagagccccgcttcatctcagtgggctacgtggacgacacgcagttcgtgcggttcgacagcgacgccgcgagtccgagaggggagccgcgggcgccgtgggtggagcaggaggggccggagtattgggaccgggagacacagaagtacaagcgccaggcacaggctgaccgagtgagcctgcggaacctgcgcggctactacaaccagagcgaggacgggtctcacaccctccagaggatgtctggctgcgacctggggcccgacgggcgcctcctccgcgggtatgaccagtccgcctacgacggcaaggattacatcgccctgaacgaggacctgcgctcctggaccgccgcggacaccgcggctcagatcacccagcgcaagttggaggcggcccgtgcggcggagcagctgagagcctacctggagggcacgtgcgtggagtggctccgcagatacctggagaacgggaaggagacgctgcagcgcgcagaacccccaaagacacacgtgacccaccaccccctctctgaccatgaggccaccctgaggtgctgggccctgggcttctaccctgcggagatcacactgacctggcagcgggatggggaggaccagacccaggacaccgagcttgtggagaccaggccagcaggagatggaaccttccagaagtgggcagctgtggtggtgccttctggacaagagcagagatacacgtgccatatgcagcacgaggggctgcaagagcccctcaccctgagctgggagccatcttcccagcccaccatccccatcatgggcatcgttgctggcctggctgtcctggttgtcctagctgtccttggagctgtggtcaccgctatgatgtgtaggaggaagagctcaggtggaaaaggagggagctgctctcaggctgcgtgcagcaacagtgcccagggctctgatgagtctctcatcacttgtaaagcctgagacagctgcctgtgtgggactgagatgcaggatttcttcacacctctcctttgtgacttcaagagcctctggcatctctttctgcaaaggcacctgaatgtgtctgcgttcctgttagcataatgtgaggaggtggagagacagcccacccccgtgtccaccgtgacccctgtccccacactgacctgtgttccctccccgatcatctttcctgttccagagaggtggggctggatgtctccatctctgtctcaaattcatggtgcactgagctgcaacttcttacttccctaatgaagttaagaacctgaatataaatttgtgttctcaaatatttgctatgaagcgttgatggattaattaaataagtcaattcctagaagttgagagagcaaataaagacctgagaaccttccagaa'
			Alignment (Snpeff CDS vs Reference CDS).	Score: 1007	Max. possible score: 1089	Diff: 82
			-----------------------------------------------------------------ATGCGGGTCATGGCGCCCCGAACCCTCATCCTGCTGCTCTCGGGAGCCCTGGCCCTGACCGAGACCTGGGCCTGCTCCCACTCCATGAGGTATTTCTACACCGCCGTGTCCCGGCCCGGCCGCGGAGAGCCCCGCTTCATCGCAGTGGGCTACGTGGACGACACGCAGTTCGTGCGGTTCGACAGCGACGCCGCGAGTCCAAGAGGGGAGCCGCGGGCGCCGTGGGTGGAGCAGGAGGGGCCGGAGTATTGGGACCGGGAGACACAGAAGTACAAGCGCCAGGCACAGACTGACCGAGTGAGCCTGCGGAACCTGCGCGGCTACTACAACCAGAGCGAGGCCGGGTCTCACACCCTCCAGTGGATGTATGGCTGCGACCTGGGGCCCGACGGGCGCCTCCTCCGCGGGTATGACCAGTCCGCCTACGACGGCAAGGATTACATCGCCCTGAACGAGGACCTGCGCTCCTGGACCGCCGCGGACACGGCGGCTCAGATCACCCAGCGCAAGTGGGAGGCGGCCCGTGCGGCGGAGCAGCAGAGAGCCTACCTGGAGGGCACGTGCGTGGAGTGGCTCCGCAGATACCTGGAGAACGGGAAGGAGACGCTGCAGCGCGCAGAACACCCAAAGACACACGTGACCCACCATCTCGTCTCTGACCATGAGGCCACCCTGAGGTGCTGGGCCCTGGGCTTCTACCCTGCGGAGATCACACTGACCTGGCAGCGGGATGGCGAGGACCAAACTCAGGACACCGAGCTTGTGGAGACCAGGCCAGCAGGAGATGGAACCTTCCAGAAGTGGGCAGCTGTGGTGGTGCCTTCTGGAGAAGAGCAGAGATACACGTGCCATGTGCAGCACGAGGGGCTGCCGGAGCCCCTCACCCTGAGATGGGAGCCATCTTCCCAGCCCACCATCCCCATCGTGGGCATCGTTGCTGGCCTGGCTGTCCTGGCTGTCCTAGCTGTCCTAGGAGCTGTGGT----G-T--G-T----AGGAGGAAGAGCTCAGGTGGAAAAGGAGGGAGCTGCTCTCAGGCTGCGTGCAGCAACAGTGCCCAGGGCTCTGATGAGTCTCTCATCGCTTGTAAAGCCTGA                                                                                                                                                                                                                                                                                                                                                                                                                                    
																			 |||||||||||||||||||||*|||||*||||||||||||||||||*|||||||||||||||||||||||||||||||||||||||||||||||||*||||||||||||||||||||||||||||||||||||||||||||*||||||||||||||||||||||||||||||||||||||||||||||||||||||||||*|||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||*|||||||||||||||||||||||||||||||||||||||||||||||||||*|||||||||||||||||||*||||||*|||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||*|||||||||||||||||||||||||*||||||||||||||||||||||||||*|||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||*||||||||||||||||||||||||*|*|*||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||*||||||||*||*|||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||*|||||||||||||||||||||||*||||||||||||||||||**|||||||||||||||||*|||||||||||||||||||||||||||||||||*||||||||||||||||||||||||||||||*|||||||||||||||*|||||||||||    | |  | |    |||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||*||||||||||||||                                                                                                                                                                                                                                                                                                                                                                                                                                    
			TCCGCAGTCCCGGTTCTAAAGTCCCCAGTCACCCACCCGGACTCACATTCTCCCCAGAGGCCGAGATGCGGGTCATGGCGCCCCGAGCCCTCCTCCTGCTGCTCTCGGGAGGCCTGGCCCTGACCGAGACCTGGGCCTGCTCCCACTCCATGAGGTATTTCGACACCGCCGTGTCCCGGCCCGGCCGCGGAGAGCCCCGCTTCATCTCAGTGGGCTACGTGGACGACACGCAGTTCGTGCGGTTCGACAGCGACGCCGCGAGTCCGAGAGGGGAGCCGCGGGCGCCGTGGGTGGAGCAGGAGGGGCCGGAGTATTGGGACCGGGAGACACAGAAGTACAAGCGCCAGGCACAGGCTGACCGAGTGAGCCTGCGGAACCTGCGCGGCTACTACAACCAGAGCGAGGACGGGTCTCACACCCTCCAGAGGATGTCTGGCTGCGACCTGGGGCCCGACGGGCGCCTCCTCCGCGGGTATGACCAGTCCGCCTACGACGGCAAGGATTACATCGCCCTGAACGAGGACCTGCGCTCCTGGACCGCCGCGGACACCGCGGCTCAGATCACCCAGCGCAAGTTGGAGGCGGCCCGTGCGGCGGAGCAGCTGAGAGCCTACCTGGAGGGCACGTGCGTGGAGTGGCTCCGCAGATACCTGGAGAACGGGAAGGAGACGCTGCAGCGCGCAGAACCCCCAAAGACACACGTGACCCACCACCCCCTCTCTGACCATGAGGCCACCCTGAGGTGCTGGGCCCTGGGCTTCTACCCTGCGGAGATCACACTGACCTGGCAGCGGGATGGGGAGGACCAGACCCAGGACACCGAGCTTGTGGAGACCAGGCCAGCAGGAGATGGAACCTTCCAGAAGTGGGCAGCTGTGGTGGTGCCTTCTGGACAAGAGCAGAGATACACGTGCCATATGCAGCACGAGGGGCTGCAAGAGCCCCTCACCCTGAGCTGGGAGCCATCTTCCCAGCCCACCATCCCCATCATGGGCATCGTTGCTGGCCTGGCTGTCCTGGTTGTCCTAGCTGTCCTTGGAGCTGTGGTCACCGCTATGATGTGTAGGAGGAAGAGCTCAGGTGGAAAAGGAGGGAGCTGCTCTCAGGCTGCGTGCAGCAACAGTGCCCAGGGCTCTGATGAGTCTCTCATCACTTGTAAAGCCTGA                                                                                                                                                                                                                                                                                                                                                                                                                                    
		Transcript details:
		6_GL000253v2_alt:2577800-2581177, strand: -, id:NM_002117.5, Protein
				5'UTR   :	6_GL000253v2_alt	2581113-2581177 UTR_5_PRIME 'NM_002117.5.ex.9'
				Exons:
				6_GL000253v2_alt:2577800-2578222 'NM_002117.5.ex.1', rank: 9, frame: 2, sequence: cctgagacagctgcctgtgtgggactgagatgcaggatttcttcacacctctcctttgtgacttcaagagcctctggcatctctttctgcaaaggcatctgaatgcgtctgcgttcctgttagcataatgtgaggaggtggagagacagcccacccccgtgtccaccgtgacccctgtccccacactgacctgtgttccctccccgatcatctttcctgttccagagaagtgggctggatgtctccatctctgtctcaactttacgtgtactgagctgcaacttcttacttccctactgaaaataagaatctgaatataaatttgttttctcaaatatttgctatgagaggttgatggattaattaaataagtcaatccctggaagttgagagagcaaataaagacctgagaaccttccagaa
				6_GL000253v2_alt:2578387-2578433 'NM_002117.5.ex.2', rank: 8, frame: 1, sequence: cagcaacagtgcccagggctctgatgagtctctcatcgcttgtaaag
				6_GL000253v2_alt:2578541-2578574 'NM_002117.5.ex.3', rank: 7, frame: 2, sequence: gtggaaaaggagggagctgctctcaggctgcgtg
				6_GL000253v2_alt:2579014-2579033 'NM_002117.5.ex.4', rank: 6, frame: 1, sequence: gtgtaggaggaagagctcag
				6_GL000253v2_alt:2579046-2579133 'NM_002117.5.ex.5', rank: 5, frame: 2, sequence: agccatcttcccagcccaccatccccatcgtgggcatcgttgctggcctggctgtcctggctgtcctagctgtcctaggagctgtggt
				6_GL000253v2_alt:2579255-2579532 'NM_002117.5.ex.6', rank: 4, frame: 1, sequence: agaacacccaaagacacacgtgacccaccatctcgtctctgaccatgaggccaccctgaggtgctgggccctgggcttctaccctgcggagatcacactgacctggcagcgggatggcgaggaccaaactcaggacaccgagcttgtggagaccaggccagcaggagatggaaccttccagaagtgggcagctgtggtggtgccttctggagaagagcagagatacacgtgccatgtgcagcacgaggggctgccggagcccctcaccctgagatggg
				6_GL000253v2_alt:2580120-2580393 'NM_002117.5.ex.7', rank: 3, frame: 2, sequence: ggtctcacaccctccagtggatgtatggctgcgacctggggcccgacgggcgcctcctccgcgggtatgaccagtccgcctacgacggcaaggattacatcgccctgaacgaggacctgcgctcctggaccgccgcggacacggcggctcagatcacccagcgcaagtgggaggcggcccgtgcggcggagcagcagagagcctacctggagggcacgtgcgtggagtggctccgcagatacctggagaacgggaaggagacgctgcagcgcgc
				6_GL000253v2_alt:2580640-2580909 'NM_002117.5.ex.8', rank: 2, frame: 2, sequence: gctcccactccatgaggtatttctacaccgccgtgtcccggcccggccgcggagagccccgcttcatcgcagtgggctacgtggacgacacgcagttcgtgcggttcgacagcgacgccgcgagtccaagaggggagccgcgggcgccgtgggtggagcaggaggggccggagtattgggaccgggagacacagaagtacaagcgccaggcacagactgaccgagtgagcctgcggaacctgcgcggctactacaaccagagcgaggccg
				6_GL000253v2_alt:2581040-2581177 'NM_002117.5.ex.9', rank: 1, frame: 0, sequence: tccgcagtcccggttctaaagtccccagtcacccacccggactcggattctccccagacgccgagatgcgggtcatggcgccccgaaccctcatcctgctgctctcgggagccctggccctgaccgagacctgggcct
				3'UTR   :	6_GL000253v2_alt	2577800-2578217 UTR_3_PRIME 'NM_002117.5.ex.1'
				CDS     :	atgcgggtcatggcgccccgaaccctcatcctgctgctctcgggagccctggccctgaccgagacctgggcctgctcccactccatgaggtatttctacaccgccgtgtcccggcccggccgcggagagccccgcttcatcgcagtgggctacgtggacgacacgcagttcgtgcggttcgacagcgacgccgcgagtccaagaggggagccgcgggcgccgtgggtggagcaggaggggccggagtattgggaccgggagacacagaagtacaagcgccaggcacagactgaccgagtgagcctgcggaacctgcgcggctactacaaccagagcgaggccgggtctcacaccctccagtggatgtatggctgcgacctggggcccgacgggcgcctcctccgcgggtatgaccagtccgcctacgacggcaaggattacatcgccctgaacgaggacctgcgctcctggaccgccgcggacacggcggctcagatcacccagcgcaagtgggaggcggcccgtgcggcggagcagcagagagcctacctggagggcacgtgcgtggagtggctccgcagatacctggagaacgggaaggagacgctgcagcgcgcagaacacccaaagacacacgtgacccaccatctcgtctctgaccatgaggccaccctgaggtgctgggccctgggcttctaccctgcggagatcacactgacctggcagcgggatggcgaggaccaaactcaggacaccgagcttgtggagaccaggccagcaggagatggaaccttccagaagtgggcagctgtggtggtgccttctggagaagagcagagatacacgtgccatgtgcagcacgaggggctgccggagcccctcaccctgagatgggagccatcttcccagcccaccatccccatcgtgggcatcgttgctggcctggctgtcctggctgtcctagctgtcctaggagctgtggtgtgtaggaggaagagctcaggtggaaaaggagggagctgctctcaggctgcgtgcagcaacagtgcccagggctctgatgagtctctcatcgcttgtaaagcctga
				Protein :	MRVMAPRTLILLLSGALALTETWACSHSMRYFYTAVSRPGRGEPRFIAVGYVDDTQFVRFDSDAASPRGEPRAPWVEQEGPEYWDRETQKYKRQAQTDRVSLRNLRGYYNQSEAGSHTLQWMYGCDLGPDGRLLRGYDQSAYDGKDYIALNEDLRSWTAADTAAQITQRKWEAARAAEQQRAYLEGTCVEWLRRYLENGKETLQRAEHPKTHVTHHLVSDHEATLRCWALGFYPAEITLTWQRDGEDQTQDTELVETRPAGDGTFQKWAAVVVPSGEEQRYTCHVQHEGLPEPLTLRWEPSSQPTIPIVGIVAGLAVLAVLAVLGAVVCRRKSSGGKGGSCSQAACSNSAQGSDESLIACKA*

6_GL000254v2_alt

		ERROR: CDSs do not match for transcript NM_002117.5	Strand:true	Exons: 8
			SnpEff CDS  (  1101) : 'atgcgggtcatggcgccccgaaccctcatcctgctgctctcgggagccctggccctgaccgagacctgggccggctcccactccatgaggtatttctacaccgctgtgtcccggcccggccgcggggagccccacttcatcgcagtgggctacgtggacgacacgcagttcgtgcggttcgacagcgacgccgcgagtccgagaggggagccgcgggcgccgtgggtggagcaggaggggccggagtattgggaccgggagacacagaagtacaagcgccaggcacagactgaccgagtgagcctgcggaacctgcgcggctactacaaccagagcgaggccgggtctcacatcatccagaggatgtatggctgcgacgtggggcccgacgggcgcctcctccgcgggtatgaccagtacgcctacgacggcaaggattacatcgccctgaacgaggatctgcgctcctggaccgccgcggacacggcggctcagatcacccagcgcaagtgggaggcggcccgtgaggcggagcagctgagagcctacctggagggcctgtgcgtggagtggctccgcagatacctgaagaatgggaaggagacgctgcagcgcgcagaacacccaaagacacacgtgacccaccatcccgtctctgaccatgaggccaccctgaggtgctgggccctgggcttctaccctgcggagatcacactgacctggcagtgggatggggaggaccaaactcaggacactgagcttgtggagaccaggccagcaggagatggaaccttccagaagtgggcagctgtggtggtgccttctggagaagagcagagatacacgtgccatgtgcagcacgaggggctgccggagcccctcaccctgagatgggagccgtcttcccagcccaccatccccatcgtgggcatcgttgctggcctggctgtcctggctgtcctagctgtcctaggagctgtggtggctgttgtgatgtgtaggaggaagagctcaggtggaaaaggagggagctgctctcaggctgcgtgcagcaacagtgcccagggctctgatgagtctctcatcgcttgtaaagcctga'
			Reference   (  1586) : 'tccgcagtcccggttctaaagtccccagtcacccacccggactcacattctccccagaggccgagatgcgggtcatggcgccccgagccctcctcctgctgctctcgggaggcctggccctgaccgagacctgggcctgctcccactccatgaggtatttcgacaccgccgtgtcccggcccggccgcggagagccccgcttcatctcagtgggctacgtggacgacacgcagttcgtgcggttcgacagcgacgccgcgagtccgagaggggagccgcgggcgccgtgggtggagcaggaggggccggagtattgggaccgggagacacagaagtacaagcgccaggcacaggctgaccgagtgagcctgcggaacctgcgcggctactacaaccagagcgaggacgggtctcacaccctccagaggatgtctggctgcgacctggggcccgacgggcgcctcctccgcgggtatgaccagtccgcctacgacggcaaggattacatcgccctgaacgaggacctgcgctcctggaccgccgcggacaccgcggctcagatcacccagcgcaagttggaggcggcccgtgcggcggagcagctgagagcctacctggagggcacgtgcgtggagtggctccgcagatacctggagaacgggaaggagacgctgcagcgcgcagaacccccaaagacacacgtgacccaccaccccctctctgaccatgaggccaccctgaggtgctgggccctgggcttctaccctgcggagatcacactgacctggcagcgggatggggaggaccagacccaggacaccgagcttgtggagaccaggccagcaggagatggaaccttccagaagtgggcagctgtggtggtgccttctggacaagagcagagatacacgtgccatatgcagcacgaggggctgcaagagcccctcaccctgagctgggagccatcttcccagcccaccatccccatcatgggcatcgttgctggcctggctgtcctggttgtcctagctgtccttggagctgtggtcaccgctatgatgtgtaggaggaagagctcaggtggaaaaggagggagctgctctcaggctgcgtgcagcaacagtgcccagggctctgatgagtctctcatcacttgtaaagcctgagacagctgcctgtgtgggactgagatgcaggatttcttcacacctctcctttgtgacttcaagagcctctggcatctctttctgcaaaggcacctgaatgtgtctgcgttcctgttagcataatgtgaggaggtggagagacagcccacccccgtgtccaccgtgacccctgtccccacactgacctgtgttccctccccgatcatctttcctgttccagagaggtggggctggatgtctccatctctgtctcaaattcatggtgcactgagctgcaacttcttacttccctaatgaagttaagaacctgaatataaatttgtgttctcaaatatttgctatgaagcgttgatggattaattaaataagtcaattcctagaagttgagagagcaaataaagacctgagaaccttccagaa'
			Alignment (Snpeff CDS vs Reference CDS).	Score: 1009	Max. possible score: 1101	Diff: 92
			-----------------------------------------------------------------ATGCGGGTCATGGCGCCCCGAACCCTCATCCTGCTGCTCTCGGGAGCCCTGGCCCTGACCGAGACCTGGGCCGGCTCCCACTCCATGAGGTATTTCTACACCGCTGTGTCCCGGCCCGGCCGCGGGGAGCCCCACTTCATCGCAGTGGGCTACGTGGACGACACGCAGTTCGTGCGGTTCGACAGCGACGCCGCGAGTCCGAGAGGGGAGCCGCGGGCGCCGTGGGTGGAGCAGGAGGGGCCGGAGTATTGGGACCGGGAGACACAGAAGTACAAGCGCCAGGCACAGACTGACCGAGTGAGCCTGCGGAACCTGCGCGGCTACTACAACCAGAGCGAGGCCGGGTCTCACATCATCCAGAGGATGTATGGCTGCGACGTGGGGCCCGACGGGCGCCTCCTCCGCGGGTATGACCAGTACGCCTACGACGGCAAGGATTACATCGCCCTGAACGAGGATCTGCGCTCCTGGACCGCCGCGGACACGGCGGCTCAGATCACCCAGCGCAAGTGGGAGGCGGCCCGTGAGGCGGAGCAGCTGAGAGCCTACCTGGAGGGCCTGTGCGTGGAGTGGCTCCGCAGATACCTGAAGAATGGGAAGGAGACGCTGCAGCGCGCAGAACACCCAAAGACACACGTGACCCACCATCCCGTCTCTGACCATGAGGCCACCCTGAGGTGCTGGGCCCTGGGCTTCTACCCTGCGGAGATCACACTGACCTGGCAGTGGGATGGGGAGGACCAAACTCAGGACACTGAGCTTGTGGAGACCAGGCCAGCAGGAGATGGAACCTTCCAGAAGTGGGCAGCTGTGGTGGTGCCTTCTGGAGAAGAGCAGAGATACACGTGCCATGTGCAGCACGAGGGGCTGCCGGAGCCCCTCACCCTGAGATGGGAGCCGTCTTCCCAGCCCACCATCCCCATCGTGGGCATCGTTGCTGGCCTGGCTGTCCTGGCTGTCCTAGCTGTCCTAGGAGCTGTGGTGGCTGTTGTGATGTGTAGGAGGAAGAGCTCAGGTGGAAAAGGAGGGAGCTGCTCTCAGGCTGCGTGCAGCAACAGTGCCCAGGGCTCTGATGAGTCTCTCATCGCTTGTAAAGCCTGA                                                                                                                                                                                                                                                                                                                                                                                                                                    
																			 |||||||||||||||||||||*|||||*||||||||||||||||||*|||||||||||||||||||||||||*|||||||||||||||||||||||*|||||||*||||||||||||||||||||*|||||||*|||||||*||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||*|||||||||||||||||||||||||||||||||||||||||||||||||||*|||||||||||*|*||||||||||||*||||||||||*|||||||||||||||||||||||||||||||||||||||*|||||||||||||||||||||||||||||||||||||||*||||||||||||||||||||||||||*|||||||||||||||||||||||||*||||||||||||||*|||||||||||||||||||||||||||||||**||||||||||||||||||||||||||||*||||*||||||||||||||||||||||||||||*||||||||||||||||||||||||*|||*||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||*||||||||||||||||*||*||||||||*||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||*|||||||||||||||||||||||*||||||||||||||||||**|||||||||||||||||*||||||||*||||||||||||||||||||||||*||||||||||||||||||||||||||||||*|||||||||||||||*|||||||||||**|*|*|*|||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||*||||||||||||||                                                                                                                                                                                                                                                                                                                                                                                                                                    
			TCCGCAGTCCCGGTTCTAAAGTCCCCAGTCACCCACCCGGACTCACATTCTCCCCAGAGGCCGAGATGCGGGTCATGGCGCCCCGAGCCCTCCTCCTGCTGCTCTCGGGAGGCCTGGCCCTGACCGAGACCTGGGCCTGCTCCCACTCCATGAGGTATTTCGACACCGCCGTGTCCCGGCCCGGCCGCGGAGAGCCCCGCTTCATCTCAGTGGGCTACGTGGACGACACGCAGTTCGTGCGGTTCGACAGCGACGCCGCGAGTCCGAGAGGGGAGCCGCGGGCGCCGTGGGTGGAGCAGGAGGGGCCGGAGTATTGGGACCGGGAGACACAGAAGTACAAGCGCCAGGCACAGGCTGACCGAGTGAGCCTGCGGAACCTGCGCGGCTACTACAACCAGAGCGAGGACGGGTCTCACACCCTCCAGAGGATGTCTGGCTGCGACCTGGGGCCCGACGGGCGCCTCCTCCGCGGGTATGACCAGTCCGCCTACGACGGCAAGGATTACATCGCCCTGAACGAGGACCTGCGCTCCTGGACCGCCGCGGACACCGCGGCTCAGATCACCCAGCGCAAGTTGGAGGCGGCCCGTGCGGCGGAGCAGCTGAGAGCCTACCTGGAGGGCACGTGCGTGGAGTGGCTCCGCAGATACCTGGAGAACGGGAAGGAGACGCTGCAGCGCGCAGAACCCCCAAAGACACACGTGACCCACCACCCCCTCTCTGACCATGAGGCCACCCTGAGGTGCTGGGCCCTGGGCTTCTACCCTGCGGAGATCACACTGACCTGGCAGCGGGATGGGGAGGACCAGACCCAGGACACCGAGCTTGTGGAGACCAGGCCAGCAGGAGATGGAACCTTCCAGAAGTGGGCAGCTGTGGTGGTGCCTTCTGGACAAGAGCAGAGATACACGTGCCATATGCAGCACGAGGGGCTGCAAGAGCCCCTCACCCTGAGCTGGGAGCCATCTTCCCAGCCCACCATCCCCATCATGGGCATCGTTGCTGGCCTGGCTGTCCTGGTTGTCCTAGCTGTCCTTGGAGCTGTGGTCACCGCTATGATGTGTAGGAGGAAGAGCTCAGGTGGAAAAGGAGGGAGCTGCTCTCAGGCTGCGTGCAGCAACAGTGCCCAGGGCTCTGATGAGTCTCTCATCACTTGTAAAGCCTGA                                                                                                                                                                                                                                                                                                                                                                                                                                    
		Transcript details:
		6_GL000254v2_alt:2611477-2614854, strand: -, id:NM_002117.5, Protein
				5'UTR   :	6_GL000254v2_alt	2614790-2614854 UTR_5_PRIME 'NM_002117.5.ex.8'
				Exons:
				6_GL000254v2_alt:2611477-2611900 'NM_002117.5.ex.1', rank: 8, frame: 2, sequence: cctgagacagctgcctgtgtgggactgagatgcaggatttcttcacacctctcctttgtgacttcaagagcctctggcatctctttctgcaaaggcatctgaatgtgtctgcgttcctgttagcataatgtgaggaggtggagagacagcccacccccgtgtccaccgtgacccctgtccccacactgacctgtgttccctccccgatcatctttcctgttccagagaagtgggctggatgtctccatctctgtctcaacttcatggtgcgctgagctgcaacttcttacttccctaatgaagttaggaacctgaatataaatttgttttctcaaatatttgctatgaagggttgatggattaattaaataagtcaattcctggaagttgagagagcaaataaagacctgagaactttccagaa
				6_GL000254v2_alt:2612065-2612111 'NM_002117.5.ex.2', rank: 7, frame: 1, sequence: cagcaacagtgcccagggctctgatgagtctctcatcgcttgtaaag
				6_GL000254v2_alt:2612219-2612252 'NM_002117.5.ex.3', rank: 6, frame: 2, sequence: gtggaaaaggagggagctgctctcaggctgcgtg
				6_GL000254v2_alt:2612692-2612811 'NM_002117.5.ex.4', rank: 5, frame: 2, sequence: agccgtcttcccagcccaccatccccatcgtgggcatcgttgctggcctggctgtcctggctgtcctagctgtcctaggagctgtggtggctgttgtgatgtgtaggaggaagagctcag
				6_GL000254v2_alt:2612933-2613210 'NM_002117.5.ex.5', rank: 4, frame: 1, sequence: agaacacccaaagacacacgtgacccaccatcccgtctctgaccatgaggccaccctgaggtgctgggccctgggcttctaccctgcggagatcacactgacctggcagtgggatggggaggaccaaactcaggacactgagcttgtggagaccaggccagcaggagatggaaccttccagaagtgggcagctgtggtggtgccttctggagaagagcagagatacacgtgccatgtgcagcacgaggggctgccggagcccctcaccctgagatggg
				6_GL000254v2_alt:2613798-2614071 'NM_002117.5.ex.6', rank: 3, frame: 2, sequence: ggtctcacatcatccagaggatgtatggctgcgacgtggggcccgacgggcgcctcctccgcgggtatgaccagtacgcctacgacggcaaggattacatcgccctgaacgaggatctgcgctcctggaccgccgcggacacggcggctcagatcacccagcgcaagtgggaggcggcccgtgaggcggagcagctgagagcctacctggagggcctgtgcgtggagtggctccgcagatacctgaagaatgggaaggagacgctgcagcgcgc
				6_GL000254v2_alt:2614317-2614586 'NM_002117.5.ex.7', rank: 2, frame: 2, sequence: gctcccactccatgaggtatttctacaccgctgtgtcccggcccggccgcggggagccccacttcatcgcagtgggctacgtggacgacacgcagttcgtgcggttcgacagcgacgccgcgagtccgagaggggagccgcgggcgccgtgggtggagcaggaggggccggagtattgggaccgggagacacagaagtacaagcgccaggcacagactgaccgagtgagcctgcggaacctgcgcggctactacaaccagagcgaggccg
				6_GL000254v2_alt:2614717-2614854 'NM_002117.5.ex.8', rank: 1, frame: 0, sequence: tccgcagtcccggttctgaagtccccagtcacccacccggactcagattctccccagacgccgagatgcgggtcatggcgccccgaaccctcatcctgctgctctcgggagccctggccctgaccgagacctgggccg
				3'UTR   :	6_GL000254v2_alt	2611477-2611895 UTR_3_PRIME 'NM_002117.5.ex.1'
				CDS     :	atgcgggtcatggcgccccgaaccctcatcctgctgctctcgggagccctggccctgaccgagacctgggccggctcccactccatgaggtatttctacaccgctgtgtcccggcccggccgcggggagccccacttcatcgcagtgggctacgtggacgacacgcagttcgtgcggttcgacagcgacgccgcgagtccgagaggggagccgcgggcgccgtgggtggagcaggaggggccggagtattgggaccgggagacacagaagtacaagcgccaggcacagactgaccgagtgagcctgcggaacctgcgcggctactacaaccagagcgaggccgggtctcacatcatccagaggatgtatggctgcgacgtggggcccgacgggcgcctcctccgcgggtatgaccagtacgcctacgacggcaaggattacatcgccctgaacgaggatctgcgctcctggaccgccgcggacacggcggctcagatcacccagcgcaagtgggaggcggcccgtgaggcggagcagctgagagcctacctggagggcctgtgcgtggagtggctccgcagatacctgaagaatgggaaggagacgctgcagcgcgcagaacacccaaagacacacgtgacccaccatcccgtctctgaccatgaggccaccctgaggtgctgggccctgggcttctaccctgcggagatcacactgacctggcagtgggatggggaggaccaaactcaggacactgagcttgtggagaccaggccagcaggagatggaaccttccagaagtgggcagctgtggtggtgccttctggagaagagcagagatacacgtgccatgtgcagcacgaggggctgccggagcccctcaccctgagatgggagccgtcttcccagcccaccatccccatcgtgggcatcgttgctggcctggctgtcctggctgtcctagctgtcctaggagctgtggtggctgttgtgatgtgtaggaggaagagctcaggtggaaaaggagggagctgctctcaggctgcgtgcagcaacagtgcccagggctctgatgagtctctcatcgcttgtaaagcctga
				Protein :	MRVMAPRTLILLLSGALALTETWAGSHSMRYFYTAVSRPGRGEPHFIAVGYVDDTQFVRFDSDAASPRGEPRAPWVEQEGPEYWDRETQKYKRQAQTDRVSLRNLRGYYNQSEAGSHIIQRMYGCDVGPDGRLLRGYDQYAYDGKDYIALNEDLRSWTAADTAAQITQRKWEAAREAEQLRAYLEGLCVEWLRRYLKNGKETLQRAEHPKTHVTHHPVSDHEATLRCWALGFYPAEITLTWQWDGEDQTQDTELVETRPAGDGTFQKWAAVVVPSGEEQRYTCHVQHEGLPEPLTLRWEPSSQPTIPIVGIVAGLAVLAVLAVLGAVVAVVMCRRKSSGGKGGSCSQAACSNSAQGSDESLIACKA*


6_GL000255v2_alt

		Frame correction: Position Transcript_6_GL000255v2_alt:2524181-2527558Transcript 'NM_002117.5.2'	Exon rank 6	Expected frame: 0	Exon frame: 2	Sequence len: 981

		ERROR: CDSs do not match for transcript NM_002117.5	Strand:true	Exons: 9
			SnpEff CDS  (  1089) : 'atgcgggtcatggcgccccgaaccctcatcctgctgctctcgggagccctggccctgaccgagacctgggcctgctcccactccatgaggtatttctacaccgccgtgtcccggcccggccgcggagagccccgcttcatcgcagtgggctacgtggacgacacgcagttcgtgcagttcgacagcgacgccgcgagtccaagaggggagccgcgggcgccgtgggtggagcaggaggggccggagtattgggaccgggagacacagaagtacaagcgccaggcacagactgaccgagtgaacctgcggaaactgcgcggctactacaaccagagcgaggccgggtctcacaccctccagaggatgtatggctgcgacctggggcccgacgggcgcctcctccgcgggtataaccagttcgcctacgacggcaaggattacatcgccctgaatgaggacctgcgctcctggaccgccgcggacaaggcggctcagatcacccagcgcaagtgggaggcggcccgtgaggcggagcagcggagagcctacctggagggcacgtgcgtggagtggctccgcagatacctggagaacgggaagaagacgctgcagcgcgcagaacacccaaagacacacgtgacccaccatcccgtctctgaccatgaggccaccctgaggtgctgggccctgggcttctaccctgcggagatcacactgacctggcagcgggatggcgaggaccaaactcaggacaccgagcttgtggagaccaggccagcaggagatggaaccttccagaagtgggcagctgtggtggtgccttctggagaagagcagagatacacgtgccatgtgcagcacgaggggctgccagagcccctcaccctgagatgggggccatcttcccagcccaccatccccatcgtgggcatcgttgctggcctggctgtcctggctgtcctagctgtcctaggagctgtgatgtgtaggaggaagagctcaggtggaaaaggagggagctgctctcaggctgcgtgcagcaacagtgcccagggctctgatgagtctctcatcgcttgtaaagcctga'
			Reference   (  1586) : 'tccgcagtcccggttctaaagtccccagtcacccacccggactcacattctccccagaggccgagatgcgggtcatggcgccccgagccctcctcctgctgctctcgggaggcctggccctgaccgagacctgggcctgctcccactccatgaggtatttcgacaccgccgtgtcccggcccggccgcggagagccccgcttcatctcagtgggctacgtggacgacacgcagttcgtgcggttcgacagcgacgccgcgagtccgagaggggagccgcgggcgccgtgggtggagcaggaggggccggagtattgggaccgggagacacagaagtacaagcgccaggcacaggctgaccgagtgagcctgcggaacctgcgcggctactacaaccagagcgaggacgggtctcacaccctccagaggatgtctggctgcgacctggggcccgacgggcgcctcctccgcgggtatgaccagtccgcctacgacggcaaggattacatcgccctgaacgaggacctgcgctcctggaccgccgcggacaccgcggctcagatcacccagcgcaagttggaggcggcccgtgcggcggagcagctgagagcctacctggagggcacgtgcgtggagtggctccgcagatacctggagaacgggaaggagacgctgcagcgcgcagaacccccaaagacacacgtgacccaccaccccctctctgaccatgaggccaccctgaggtgctgggccctgggcttctaccctgcggagatcacactgacctggcagcgggatggggaggaccagacccaggacaccgagcttgtggagaccaggccagcaggagatggaaccttccagaagtgggcagctgtggtggtgccttctggacaagagcagagatacacgtgccatatgcagcacgaggggctgcaagagcccctcaccctgagctgggagccatcttcccagcccaccatccccatcatgggcatcgttgctggcctggctgtcctggttgtcctagctgtccttggagctgtggtcaccgctatgatgtgtaggaggaagagctcaggtggaaaaggagggagctgctctcaggctgcgtgcagcaacagtgcccagggctctgatgagtctctcatcacttgtaaagcctgagacagctgcctgtgtgggactgagatgcaggatttcttcacacctctcctttgtgacttcaagagcctctggcatctctttctgcaaaggcacctgaatgtgtctgcgttcctgttagcataatgtgaggaggtggagagacagcccacccccgtgtccaccgtgacccctgtccccacactgacctgtgttccctccccgatcatctttcctgttccagagaggtggggctggatgtctccatctctgtctcaaattcatggtgcactgagctgcaacttcttacttccctaatgaagttaagaacctgaatataaatttgtgttctcaaatatttgctatgaagcgttgatggattaattaaataagtcaattcctagaagttgagagagcaaataaagacctgagaaccttccagaa'
			Alignment (Snpeff CDS vs Reference CDS).	Score: 993	Max. possible score: 1089	Diff: 96
			-----------------------------------------------------------------ATGCGGGTCATGGCGCCCCGAACCCTCATCCTGCTGCTCTCGGGAGCCCTGGCCCTGACCGAGACCTGGGCCTGCTCCCACTCCATGAGGTATTTCTACACCGCCGTGTCCCGGCCCGGCCGCGGAGAGCCCCGCTTCATCGCAGTGGGCTACGTGGACGACACGCAGTTCGTGCAGTTCGACAGCGACGCCGCGAGTCCAAGAGGGGAGCCGCGGGCGCCGTGGGTGGAGCAGGAGGGGCCGGAGTATTGGGACCGGGAGACACAGAAGTACAAGCGCCAGGCACAGACTGACCGAGTGAACCTGCGGAAACTGCGCGGCTACTACAACCAGAGCGAGGCCGGGTCTCACACCCTCCAGAGGATGTATGGCTGCGACCTGGGGCCCGACGGGCGCCTCCTCCGCGGGTATAACCAGTTCGCCTACGACGGCAAGGATTACATCGCCCTGAATGAGGACCTGCGCTCCTGGACCGCCGCGGACAAGGCGGCTCAGATCACCCAGCGCAAGTGGGAGGCGGCCCGTGAGGCGGAGCAGCGGAGAGCCTACCTGGAGGGCACGTGCGTGGAGTGGCTCCGCAGATACCTGGAGAACGGGAAGAAGACGCTGCAGCGCGCAGAACACCCAAAGACACACGTGACCCACCATCCCGTCTCTGACCATGAGGCCACCCTGAGGTGCTGGGCCCTGGGCTTCTACCCTGCGGAGATCACACTGACCTGGCAGCGGGATGGCGAGGACCAAACTCAGGACACCGAGCTTGTGGAGACCAGGCCAGCAGGAGATGGAACCTTCCAGAAGTGGGCAGCTGTGGTGGTGCCTTCTGGAGAAGAGCAGAGATACACGTGCCATGTGCAGCACGAGGGGCTGCCAGAGCCCCTCACCCTGAGATGGGGGCCATCTTCCCAGCCCACCATCCCCATCGTGGGCATCGTTGCTGGCCTGGCTGTCCTGGCTGTCCTAGCTGTCCTAGGAGCTGTG---A----T--G-TGT--AGGAGGAAGAGCTCAGGTGGAAAAGGAGGGAGCTGCTCTCAGGCTGCGTGCAGCAACAGTGCCCAGGGCTCTGATGAGTCTCTCATCGCTTGTAAAGCCTGA                                                                                                                                                                                                                                                                                                                                                                                                                                    
																			 |||||||||||||||||||||*|||||*||||||||||||||||||*|||||||||||||||||||||||||||||||||||||||||||||||||*||||||||||||||||||||||||||||||||||||||||||||*|||||||||||||||||||||||||||||||||*||||||||||||||||||||||||*|||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||*||||||||||||*|||||||||*||||||||||||||||||||||||||||*||||||||||||||||||||||||||*|||||||||||||||||||||||||||||||||||||||||||*||||||*|||||||||||||||||||||||||||||||||*|||||||||||||||||||||||||||||||**|||||||||||||||||||||||||*||||||||||||||*|||||||||||*|||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||*|||||||||||||||||||||*||||||||||||||||||||||||*|||*||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||*||||||||*||*|||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||*|||||||||||||||||||||||*||||||||||||||||||*||||||||||||||||||*||||*||||||||||||||||||||||||||||*||||||||||||||||||||||||||||||*|||||||||||||||*|||||||||   |    |  | |||  |||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||*||||||||||||||                                                                                                                                                                                                                                                                                                                                                                                                                                    
			TCCGCAGTCCCGGTTCTAAAGTCCCCAGTCACCCACCCGGACTCACATTCTCCCCAGAGGCCGAGATGCGGGTCATGGCGCCCCGAGCCCTCCTCCTGCTGCTCTCGGGAGGCCTGGCCCTGACCGAGACCTGGGCCTGCTCCCACTCCATGAGGTATTTCGACACCGCCGTGTCCCGGCCCGGCCGCGGAGAGCCCCGCTTCATCTCAGTGGGCTACGTGGACGACACGCAGTTCGTGCGGTTCGACAGCGACGCCGCGAGTCCGAGAGGGGAGCCGCGGGCGCCGTGGGTGGAGCAGGAGGGGCCGGAGTATTGGGACCGGGAGACACAGAAGTACAAGCGCCAGGCACAGGCTGACCGAGTGAGCCTGCGGAACCTGCGCGGCTACTACAACCAGAGCGAGGACGGGTCTCACACCCTCCAGAGGATGTCTGGCTGCGACCTGGGGCCCGACGGGCGCCTCCTCCGCGGGTATGACCAGTCCGCCTACGACGGCAAGGATTACATCGCCCTGAACGAGGACCTGCGCTCCTGGACCGCCGCGGACACCGCGGCTCAGATCACCCAGCGCAAGTTGGAGGCGGCCCGTGCGGCGGAGCAGCTGAGAGCCTACCTGGAGGGCACGTGCGTGGAGTGGCTCCGCAGATACCTGGAGAACGGGAAGGAGACGCTGCAGCGCGCAGAACCCCCAAAGACACACGTGACCCACCACCCCCTCTCTGACCATGAGGCCACCCTGAGGTGCTGGGCCCTGGGCTTCTACCCTGCGGAGATCACACTGACCTGGCAGCGGGATGGGGAGGACCAGACCCAGGACACCGAGCTTGTGGAGACCAGGCCAGCAGGAGATGGAACCTTCCAGAAGTGGGCAGCTGTGGTGGTGCCTTCTGGACAAGAGCAGAGATACACGTGCCATATGCAGCACGAGGGGCTGCAAGAGCCCCTCACCCTGAGCTGGGAGCCATCTTCCCAGCCCACCATCCCCATCATGGGCATCGTTGCTGGCCTGGCTGTCCTGGTTGTCCTAGCTGTCCTTGGAGCTGTGGTCACCGCTATGATGTGTAGGAGGAAGAGCTCAGGTGGAAAAGGAGGGAGCTGCTCTCAGGCTGCGTGCAGCAACAGTGCCCAGGGCTCTGATGAGTCTCTCATCACTTGTAAAGCCTGA                                                                                                                                                                                                                                                                                                                                                                                                                                    
		Transcript details:
		6_GL000255v2_alt:2524180-2527557, strand: -, id:NM_002117.5, Protein
				5'UTR   :	6_GL000255v2_alt	2527493-2527557 UTR_5_PRIME 'NM_002117.5.ex.9'
				Exons:
				6_GL000255v2_alt:2524180-2524602 'NM_002117.5.ex.1', rank: 9, frame: 2, sequence: cctgagacagctgcctgtgtgggactgagatgcaggatttcttcacacctttcctttgtgacttcaagagcctctggcatctctttctgcaaaggcatctgaatgtgtctgcgttcctgttagcataatgtgaggaggtggagagacagcccacccccgtgtccaccgtgacccctgtccccacactgacctgtgttccctccccgatcatctttcctgttccagagaagtgggctggatgtctccatctctgtctcaactttacgtgtactgagctgcaacttcttacttccctactgaaaataagaatctgaatataaatttgttttctcaaatatttgctatgagaggttgatggattaattaaataagtcaattcctggaagttgagagagcaaataaagacctgagaaccttccagaa
				6_GL000255v2_alt:2524767-2524813 'NM_002117.5.ex.2', rank: 8, frame: 1, sequence: cagcaacagtgcccagggctctgatgagtctctcatcgcttgtaaag
				6_GL000255v2_alt:2524921-2524954 'NM_002117.5.ex.3', rank: 7, frame: 2, sequence: gtggaaaaggagggagctgctctcaggctgcgtg
				6_GL000255v2_alt:2525394-2525415 'NM_002117.5.ex.4', rank: 6, frame: 0, sequence: atgtgtaggaggaagagctcag
				6_GL000255v2_alt:2525428-2525513 'NM_002117.5.ex.5', rank: 5, frame: 2, sequence: ggccatcttcccagcccaccatccccatcgtgggcatcgttgctggcctggctgtcctggctgtcctagctgtcctaggagctgtg
				6_GL000255v2_alt:2525635-2525912 'NM_002117.5.ex.6', rank: 4, frame: 1, sequence: agaacacccaaagacacacgtgacccaccatcccgtctctgaccatgaggccaccctgaggtgctgggccctgggcttctaccctgcggagatcacactgacctggcagcgggatggcgaggaccaaactcaggacaccgagcttgtggagaccaggccagcaggagatggaaccttccagaagtgggcagctgtggtggtgccttctggagaagagcagagatacacgtgccatgtgcagcacgaggggctgccagagcccctcaccctgagatggg
				6_GL000255v2_alt:2526500-2526773 'NM_002117.5.ex.7', rank: 3, frame: 2, sequence: ggtctcacaccctccagaggatgtatggctgcgacctggggcccgacgggcgcctcctccgcgggtataaccagttcgcctacgacggcaaggattacatcgccctgaatgaggacctgcgctcctggaccgccgcggacaaggcggctcagatcacccagcgcaagtgggaggcggcccgtgaggcggagcagcggagagcctacctggagggcacgtgcgtggagtggctccgcagatacctggagaacgggaagaagacgctgcagcgcgc
				6_GL000255v2_alt:2527020-2527289 'NM_002117.5.ex.8', rank: 2, frame: 2, sequence: gctcccactccatgaggtatttctacaccgccgtgtcccggcccggccgcggagagccccgcttcatcgcagtgggctacgtggacgacacgcagttcgtgcagttcgacagcgacgccgcgagtccaagaggggagccgcgggcgccgtgggtggagcaggaggggccggagtattgggaccgggagacacagaagtacaagcgccaggcacagactgaccgagtgaacctgcggaaactgcgcggctactacaaccagagcgaggccg
				6_GL000255v2_alt:2527420-2527557 'NM_002117.5.ex.9', rank: 1, frame: 0, sequence: tccgcagtcccggttctaaagtccccagtcacccacccggactcggattctccccagacgccgagatgcgggtcatggcgccccgaaccctcatcctgctgctctcgggagccctggccctgaccgagacctgggcct
				3'UTR   :	6_GL000255v2_alt	2524180-2524597 UTR_3_PRIME 'NM_002117.5.ex.1'
				CDS     :	atgcgggtcatggcgccccgaaccctcatcctgctgctctcgggagccctggccctgaccgagacctgggcctgctcccactccatgaggtatttctacaccgccgtgtcccggcccggccgcggagagccccgcttcatcgcagtgggctacgtggacgacacgcagttcgtgcagttcgacagcgacgccgcgagtccaagaggggagccgcgggcgccgtgggtggagcaggaggggccggagtattgggaccgggagacacagaagtacaagcgccaggcacagactgaccgagtgaacctgcggaaactgcgcggctactacaaccagagcgaggccgggtctcacaccctccagaggatgtatggctgcgacctggggcccgacgggcgcctcctccgcgggtataaccagttcgcctacgacggcaaggattacatcgccctgaatgaggacctgcgctcctggaccgccgcggacaaggcggctcagatcacccagcgcaagtgggaggcggcccgtgaggcggagcagcggagagcctacctggagggcacgtgcgtggagtggctccgcagatacctggagaacgggaagaagacgctgcagcgcgcagaacacccaaagacacacgtgacccaccatcccgtctctgaccatgaggccaccctgaggtgctgggccctgggcttctaccctgcggagatcacactgacctggcagcgggatggcgaggaccaaactcaggacaccgagcttgtggagaccaggccagcaggagatggaaccttccagaagtgggcagctgtggtggtgccttctggagaagagcagagatacacgtgccatgtgcagcacgaggggctgccagagcccctcaccctgagatgggggccatcttcccagcccaccatccccatcgtgggcatcgttgctggcctggctgtcctggctgtcctagctgtcctaggagctgtgatgtgtaggaggaagagctcaggtggaaaaggagggagctgctctcaggctgcgtgcagcaacagtgcccagggctctgatgagtctctcatcgcttgtaaagcctga
				Protein :	MRVMAPRTLILLLSGALALTETWACSHSMRYFYTAVSRPGRGEPRFIAVGYVDDTQFVQFDSDAASPRGEPRAPWVEQEGPEYWDRETQKYKRQAQTDRVNLRKLRGYYNQSEAGSHTLQRMYGCDLGPDGRLLRGYNQFAYDGKDYIALNEDLRSWTAADKAAQITQRKWEAAREAEQRRAYLEGTCVEWLRRYLENGKKTLQRAEHPKTHVTHHPVSDHEATLRCWALGFYPAEITLTWQRDGEDQTQDTELVETRPAGDGTFQKWAAVVVPSGEEQRYTCHVQHEGLPEPLTLRWGPSSQPTIPIVGIVAGLAVLAVLAVLGAVMCRRKSSGGKGGSCSQAACSNSAQGSDESLIACKA*

6_GL000256v2_alt

		Frame correction: Position Transcript_6_GL000256v2_alt:2570707-2574084Transcript 'NM_002117.5.3'	Exon rank 6	Expected frame: 0	Exon frame: 2	Sequence len: 981

		ERROR: CDSs do not match for transcript NM_002117.5	Strand:true	Exons: 9
			SnpEff CDS  (  1089) : 'atgcgggtcatggcgccccgaaccctcatcctgctgctctcgggagccctggccctgaccgagacctgggcctgctcccactccatgaggtatttctacaccgccgtgtcccggcccggccgcggagagccccgcttcatcgcagtgggctacgtggacgacacgcagttcgtgcagttcgacagcgacgccgcgagtccaagaggggagccgcgggcgccgtgggtggagcaggaggggccggagtattgggaccgggagacacagaagtacaagcgccaggcacagactgaccgagtgaacctgcggaaactgcgcggctactacaaccagagcgaggccgggtctcacaccctccagaggatgtatggctgcgacctggggcccgacgggcgcctcctccgcgggtataaccagttcgcctacgacggcaaggattacatcgccctgaatgaggacctgcgctcctggaccgccgcggacaaggcggctcagatcacccagcgcaagtgggaggcggcccgtgaggcggagcagcggagagcctacctggagggcacgtgcgtggagtggctccgcagatacctggagaacgggaagaagacgctgcagcgcgcagaacacccaaagacacacgtgacccaccatcccgtctctgaccatgaggccaccctgaggtgctgggccctgggcttctaccctgcggagatcacactgacctggcagcgggatggcgaggaccaaactcaggacaccgagcttgtggagaccaggccagcaggagatggaaccttccagaagtgggcagctgtggtggtgccttctggagaagagcagagatacacgtgccatgtgcagcacgaggggctgccagagcccctcaccctgagatgggggccatcttcccagcccaccatccccatcgtgggcatcgttgctggcctggctgtcctggctgtcctagctgtcctaggagctgtgatgtgtaggaggaagagctcaggtggaaaaggagggagctgctctcaggctgcgtgcagcaacagtgcccagggctctgatgagtctctcatcgcttgtaaagcctga'
			Reference   (  1586) : 'tccgcagtcccggttctaaagtccccagtcacccacccggactcacattctccccagaggccgagatgcgggtcatggcgccccgagccctcctcctgctgctctcgggaggcctggccctgaccgagacctgggcctgctcccactccatgaggtatttcgacaccgccgtgtcccggcccggccgcggagagccccgcttcatctcagtgggctacgtggacgacacgcagttcgtgcggttcgacagcgacgccgcgagtccgagaggggagccgcgggcgccgtgggtggagcaggaggggccggagtattgggaccgggagacacagaagtacaagcgccaggcacaggctgaccgagtgagcctgcggaacctgcgcggctactacaaccagagcgaggacgggtctcacaccctccagaggatgtctggctgcgacctggggcccgacgggcgcctcctccgcgggtatgaccagtccgcctacgacggcaaggattacatcgccctgaacgaggacctgcgctcctggaccgccgcggacaccgcggctcagatcacccagcgcaagttggaggcggcccgtgcggcggagcagctgagagcctacctggagggcacgtgcgtggagtggctccgcagatacctggagaacgggaaggagacgctgcagcgcgcagaacccccaaagacacacgtgacccaccaccccctctctgaccatgaggccaccctgaggtgctgggccctgggcttctaccctgcggagatcacactgacctggcagcgggatggggaggaccagacccaggacaccgagcttgtggagaccaggccagcaggagatggaaccttccagaagtgggcagctgtggtggtgccttctggacaagagcagagatacacgtgccatatgcagcacgaggggctgcaagagcccctcaccctgagctgggagccatcttcccagcccaccatccccatcatgggcatcgttgctggcctggctgtcctggttgtcctagctgtccttggagctgtggtcaccgctatgatgtgtaggaggaagagctcaggtggaaaaggagggagctgctctcaggctgcgtgcagcaacagtgcccagggctctgatgagtctctcatcacttgtaaagcctgagacagctgcctgtgtgggactgagatgcaggatttcttcacacctctcctttgtgacttcaagagcctctggcatctctttctgcaaaggcacctgaatgtgtctgcgttcctgttagcataatgtgaggaggtggagagacagcccacccccgtgtccaccgtgacccctgtccccacactgacctgtgttccctccccgatcatctttcctgttccagagaggtggggctggatgtctccatctctgtctcaaattcatggtgcactgagctgcaacttcttacttccctaatgaagttaagaacctgaatataaatttgtgttctcaaatatttgctatgaagcgttgatggattaattaaataagtcaattcctagaagttgagagagcaaataaagacctgagaaccttccagaa'
			Alignment (Snpeff CDS vs Reference CDS).	Score: 993	Max. possible score: 1089	Diff: 96
			-----------------------------------------------------------------ATGCGGGTCATGGCGCCCCGAACCCTCATCCTGCTGCTCTCGGGAGCCCTGGCCCTGACCGAGACCTGGGCCTGCTCCCACTCCATGAGGTATTTCTACACCGCCGTGTCCCGGCCCGGCCGCGGAGAGCCCCGCTTCATCGCAGTGGGCTACGTGGACGACACGCAGTTCGTGCAGTTCGACAGCGACGCCGCGAGTCCAAGAGGGGAGCCGCGGGCGCCGTGGGTGGAGCAGGAGGGGCCGGAGTATTGGGACCGGGAGACACAGAAGTACAAGCGCCAGGCACAGACTGACCGAGTGAACCTGCGGAAACTGCGCGGCTACTACAACCAGAGCGAGGCCGGGTCTCACACCCTCCAGAGGATGTATGGCTGCGACCTGGGGCCCGACGGGCGCCTCCTCCGCGGGTATAACCAGTTCGCCTACGACGGCAAGGATTACATCGCCCTGAATGAGGACCTGCGCTCCTGGACCGCCGCGGACAAGGCGGCTCAGATCACCCAGCGCAAGTGGGAGGCGGCCCGTGAGGCGGAGCAGCGGAGAGCCTACCTGGAGGGCACGTGCGTGGAGTGGCTCCGCAGATACCTGGAGAACGGGAAGAAGACGCTGCAGCGCGCAGAACACCCAAAGACACACGTGACCCACCATCCCGTCTCTGACCATGAGGCCACCCTGAGGTGCTGGGCCCTGGGCTTCTACCCTGCGGAGATCACACTGACCTGGCAGCGGGATGGCGAGGACCAAACTCAGGACACCGAGCTTGTGGAGACCAGGCCAGCAGGAGATGGAACCTTCCAGAAGTGGGCAGCTGTGGTGGTGCCTTCTGGAGAAGAGCAGAGATACACGTGCCATGTGCAGCACGAGGGGCTGCCAGAGCCCCTCACCCTGAGATGGGGGCCATCTTCCCAGCCCACCATCCCCATCGTGGGCATCGTTGCTGGCCTGGCTGTCCTGGCTGTCCTAGCTGTCCTAGGAGCTGTG---A----T--G-TGT--AGGAGGAAGAGCTCAGGTGGAAAAGGAGGGAGCTGCTCTCAGGCTGCGTGCAGCAACAGTGCCCAGGGCTCTGATGAGTCTCTCATCGCTTGTAAAGCCTGA                                                                                                                                                                                                                                                                                                                                                                                                                                    
																			 |||||||||||||||||||||*|||||*||||||||||||||||||*|||||||||||||||||||||||||||||||||||||||||||||||||*||||||||||||||||||||||||||||||||||||||||||||*|||||||||||||||||||||||||||||||||*||||||||||||||||||||||||*|||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||*||||||||||||*|||||||||*||||||||||||||||||||||||||||*||||||||||||||||||||||||||*|||||||||||||||||||||||||||||||||||||||||||*||||||*|||||||||||||||||||||||||||||||||*|||||||||||||||||||||||||||||||**|||||||||||||||||||||||||*||||||||||||||*|||||||||||*|||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||*|||||||||||||||||||||*||||||||||||||||||||||||*|||*||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||*||||||||*||*|||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||*|||||||||||||||||||||||*||||||||||||||||||*||||||||||||||||||*||||*||||||||||||||||||||||||||||*||||||||||||||||||||||||||||||*|||||||||||||||*|||||||||   |    |  | |||  |||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||*||||||||||||||                                                                                                                                                                                                                                                                                                                                                                                                                                    
			TCCGCAGTCCCGGTTCTAAAGTCCCCAGTCACCCACCCGGACTCACATTCTCCCCAGAGGCCGAGATGCGGGTCATGGCGCCCCGAGCCCTCCTCCTGCTGCTCTCGGGAGGCCTGGCCCTGACCGAGACCTGGGCCTGCTCCCACTCCATGAGGTATTTCGACACCGCCGTGTCCCGGCCCGGCCGCGGAGAGCCCCGCTTCATCTCAGTGGGCTACGTGGACGACACGCAGTTCGTGCGGTTCGACAGCGACGCCGCGAGTCCGAGAGGGGAGCCGCGGGCGCCGTGGGTGGAGCAGGAGGGGCCGGAGTATTGGGACCGGGAGACACAGAAGTACAAGCGCCAGGCACAGGCTGACCGAGTGAGCCTGCGGAACCTGCGCGGCTACTACAACCAGAGCGAGGACGGGTCTCACACCCTCCAGAGGATGTCTGGCTGCGACCTGGGGCCCGACGGGCGCCTCCTCCGCGGGTATGACCAGTCCGCCTACGACGGCAAGGATTACATCGCCCTGAACGAGGACCTGCGCTCCTGGACCGCCGCGGACACCGCGGCTCAGATCACCCAGCGCAAGTTGGAGGCGGCCCGTGCGGCGGAGCAGCTGAGAGCCTACCTGGAGGGCACGTGCGTGGAGTGGCTCCGCAGATACCTGGAGAACGGGAAGGAGACGCTGCAGCGCGCAGAACCCCCAAAGACACACGTGACCCACCACCCCCTCTCTGACCATGAGGCCACCCTGAGGTGCTGGGCCCTGGGCTTCTACCCTGCGGAGATCACACTGACCTGGCAGCGGGATGGGGAGGACCAGACCCAGGACACCGAGCTTGTGGAGACCAGGCCAGCAGGAGATGGAACCTTCCAGAAGTGGGCAGCTGTGGTGGTGCCTTCTGGACAAGAGCAGAGATACACGTGCCATATGCAGCACGAGGGGCTGCAAGAGCCCCTCACCCTGAGCTGGGAGCCATCTTCCCAGCCCACCATCCCCATCATGGGCATCGTTGCTGGCCTGGCTGTCCTGGTTGTCCTAGCTGTCCTTGGAGCTGTGGTCACCGCTATGATGTGTAGGAGGAAGAGCTCAGGTGGAAAAGGAGGGAGCTGCTCTCAGGCTGCGTGCAGCAACAGTGCCCAGGGCTCTGATGAGTCTCTCATCACTTGTAAAGCCTGA                                                                                                                                                                                                                                                                                                                                                                                                                                    
		Transcript details:
		6_GL000256v2_alt:2570706-2574083, strand: -, id:NM_002117.5, Protein
				5'UTR   :	6_GL000256v2_alt	2574019-2574083 UTR_5_PRIME 'NM_002117.5.ex.9'
				Exons:
				6_GL000256v2_alt:2570706-2571128 'NM_002117.5.ex.1', rank: 9, frame: 2, sequence: cctgagacagctgcctgtgtgggactgagatgcaggatttcttcacacctttcctttgtgacttcaagagcctctggcatctctttctgcaaaggcatctgaatgtgtctgcgttcctgttagcataatgtgaggaggtggagagacagcccacccccgtgtccaccgtgacccctgtccccacactgacctgtgttccctccccgatcatctttcctgttccagagaagtgggctggatgtctccatctctgtctcaactttacgtgtactgagctgcaacttcttacttccctactgaaaataagaatctgaatataaatttgttttctcaaatatttgctatgagaggttgatggattaattaaataagtcaattcctggaagttgagagagcaaataaagacctgagaaccttccagaa
				6_GL000256v2_alt:2571293-2571339 'NM_002117.5.ex.2', rank: 8, frame: 1, sequence: cagcaacagtgcccagggctctgatgagtctctcatcgcttgtaaag
				6_GL000256v2_alt:2571447-2571480 'NM_002117.5.ex.3', rank: 7, frame: 2, sequence: gtggaaaaggagggagctgctctcaggctgcgtg
				6_GL000256v2_alt:2571920-2571941 'NM_002117.5.ex.4', rank: 6, frame: 0, sequence: atgtgtaggaggaagagctcag
				6_GL000256v2_alt:2571954-2572039 'NM_002117.5.ex.5', rank: 5, frame: 2, sequence: ggccatcttcccagcccaccatccccatcgtgggcatcgttgctggcctggctgtcctggctgtcctagctgtcctaggagctgtg
				6_GL000256v2_alt:2572161-2572438 'NM_002117.5.ex.6', rank: 4, frame: 1, sequence: agaacacccaaagacacacgtgacccaccatcccgtctctgaccatgaggccaccctgaggtgctgggccctgggcttctaccctgcggagatcacactgacctggcagcgggatggcgaggaccaaactcaggacaccgagcttgtggagaccaggccagcaggagatggaaccttccagaagtgggcagctgtggtggtgccttctggagaagagcagagatacacgtgccatgtgcagcacgaggggctgccagagcccctcaccctgagatggg
				6_GL000256v2_alt:2573026-2573299 'NM_002117.5.ex.7', rank: 3, frame: 2, sequence: ggtctcacaccctccagaggatgtatggctgcgacctggggcccgacgggcgcctcctccgcgggtataaccagttcgcctacgacggcaaggattacatcgccctgaatgaggacctgcgctcctggaccgccgcggacaaggcggctcagatcacccagcgcaagtgggaggcggcccgtgaggcggagcagcggagagcctacctggagggcacgtgcgtggagtggctccgcagatacctggagaacgggaagaagacgctgcagcgcgc
				6_GL000256v2_alt:2573546-2573815 'NM_002117.5.ex.8', rank: 2, frame: 2, sequence: gctcccactccatgaggtatttctacaccgccgtgtcccggcccggccgcggagagccccgcttcatcgcagtgggctacgtggacgacacgcagttcgtgcagttcgacagcgacgccgcgagtccaagaggggagccgcgggcgccgtgggtggagcaggaggggccggagtattgggaccgggagacacagaagtacaagcgccaggcacagactgaccgagtgaacctgcggaaactgcgcggctactacaaccagagcgaggccg
				6_GL000256v2_alt:2573946-2574083 'NM_002117.5.ex.9', rank: 1, frame: 0, sequence: tccgcagtcccggttctaaagtccccagtcacccacccggactcggattctccccagacgccgagatgcgggtcatggcgccccgaaccctcatcctgctgctctcgggagccctggccctgaccgagacctgggcct
				3'UTR   :	6_GL000256v2_alt	2570706-2571123 UTR_3_PRIME 'NM_002117.5.ex.1'
				CDS     :	atgcgggtcatggcgccccgaaccctcatcctgctgctctcgggagccctggccctgaccgagacctgggcctgctcccactccatgaggtatttctacaccgccgtgtcccggcccggccgcggagagccccgcttcatcgcagtgggctacgtggacgacacgcagttcgtgcagttcgacagcgacgccgcgagtccaagaggggagccgcgggcgccgtgggtggagcaggaggggccggagtattgggaccgggagacacagaagtacaagcgccaggcacagactgaccgagtgaacctgcggaaactgcgcggctactacaaccagagcgaggccgggtctcacaccctccagaggatgtatggctgcgacctggggcccgacgggcgcctcctccgcgggtataaccagttcgcctacgacggcaaggattacatcgccctgaatgaggacctgcgctcctggaccgccgcggacaaggcggctcagatcacccagcgcaagtgggaggcggcccgtgaggcggagcagcggagagcctacctggagggcacgtgcgtggagtggctccgcagatacctggagaacgggaagaagacgctgcagcgcgcagaacacccaaagacacacgtgacccaccatcccgtctctgaccatgaggccaccctgaggtgctgggccctgggcttctaccctgcggagatcacactgacctggcagcgggatggcgaggaccaaactcaggacaccgagcttgtggagaccaggccagcaggagatggaaccttccagaagtgggcagctgtggtggtgccttctggagaagagcagagatacacgtgccatgtgcagcacgaggggctgccagagcccctcaccctgagatgggggccatcttcccagcccaccatccccatcgtgggcatcgttgctggcctggctgtcctggctgtcctagctgtcctaggagctgtgatgtgtaggaggaagagctcaggtggaaaaggagggagctgctctcaggctgcgtgcagcaacagtgcccagggctctgatgagtctctcatcgcttgtaaagcctga
				Protein :	MRVMAPRTLILLLSGALALTETWACSHSMRYFYTAVSRPGRGEPRFIAVGYVDDTQFVQFDSDAASPRGEPRAPWVEQEGPEYWDRETQKYKRQAQTDRVNLRKLRGYYNQSEAGSHTLQRMYGCDLGPDGRLLRGYNQFAYDGKDYIALNEDLRSWTAADKAAQITQRKWEAAREAEQRRAYLEGTCVEWLRRYLENGKKTLQRAEHPKTHVTHHPVSDHEATLRCWALGFYPAEITLTWQRDGEDQTQDTELVETRPAGDGTFQKWAAVVVPSGEEQRYTCHVQHEGLPEPLTLRWGPSSQPTIPIVGIVAGLAVLAVLAVLGAVMCRRKSSGGKGGSCSQAACSNSAQGSDESLIACKA*

